### ISSUE TITLE
Návrh k diskusi: Zápis verzování do arclibxml

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#102]
V průběhu testování verzování, stejně jako z tabulky zde [https://docs.google.com/spreadsheets/d/1OR_NyrTfajZo5emu4PV2c0-pA3D6s2E6lcyx2cJXzLU/edit#gid=586517350](url) jsem si několikrát všiml, že elementy `xmlVersionNumber` a `xmlVersionOf` mají v souboru `ArclibXmlGenerator.java` napevno určený xpath do DC dmdSecu. Obvykle se tedy uloží v DCMD_TITLE nebo DCMD_VOLUME, což dle mého názoru není pro tento typ informace vhodné místo, neboť zde by měla být popisná metadata. 

Rád bych proto otevřel diskusi, zda by nebylo možné umístit tyto hodnoty někam jinam, například do administrativních metadat `/METS:mets/METS:amdSec/METS:techMD/METS:mdWrap[@MDTYPE='OTHER']/METS:xmlData`  s využitím namespace ARCLIB?

**Comment by ZdenekVasek** [comment]
Dávalo by to větší smysl, souhlasím.

**Comment by godnat** [comment]
Pokud je uprava možná, také souhlasím s umístěním mimo popisná metadata, je možné použít stejné názvy elementů jako v DC, ale z namespace ARCLIB a vložit to do části ARCLIB XML, která je generovaná Arclibem. V CDA dávají info o souvisejících verzích balíčků do mets hlavičky do alrRecordID, ale ten popis tam neni tak podrobný jako ted je v ARCLIB XML v DC a je asi záměrem tuto podrobnost ponechat. V CDA se nejspíš do hlavičky uvede jen versionOf a odkaz na předchozí verzi balíku.

**Comment by yantom** [comment]
Bude implementováno přemístění.

**Comment by yantom** [comment]
Implementováno a nasazeno. Zmíněné elementy jsou v nových balících v samostatném elementu ARCLib:sipInfo.

**Comment by jbil7** [comment]
Moc děkuji! Potvrzuji na základě testu, že elementy jsou přemístěny a verzování je funkční.
