### ISSUE TITLE
aktualizace nástroje DROID

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#104]
Dobrý den,
Jak je to aktuálně s aktualizací nástroje DROID? 

Z předešlých diskuzí si pamatuji, že se aktualizuje automaticky, při každém update signature files. Myslím, že se také řešilo odkud aktualizovat, tj. co je autoritním zdrojem informací pro aktualizaci DROIDu. Odkud se nyní aktualizuje? 

V Arclibu je nyní DROID ve verzi 6.4 a signature files V91 a container signatures 20170330. xml. 

Ted by ale měla být už verze 6.5 signature file V96 a  container signatures 20200121.xml. (https://www.nationalarchives.gov.uk/information-management/manage-information/preserving-digital-records/droid/, příp. https://github.com/digital-preservation/droid/releases ) (asi měsíc stará je ta nová verze)

Ale např. tady http://digital-preservation.github.io/droid/  což je taky zdroj spravovaný tvůrcem DROIDu je ještě uvedena verze 6.4.

**Comment by yantom** [comment]
ARCLib aktualizaci Droidu neprovádí, pouze detekuje jeho novou verzi. 

V konfiguračním souboru Droidu lze nastavit automatická aktualizace signature files (pouze) prováděná při startu, ta se ale provádí nejspíše pouze při startu skrze GUI. ARCLib používa DROID přes CLI, nikoliv GUI.

Aktualizaci Droidu a jeho signature files by tedy měl vykonávat systémový administátor / script, mimo ARCLib.

**Comment by ZdenekVasek** [comment]
Zpráva o nové verzi DROID je propagována jakým způsobem?

**Comment by yantom** [comment]
Je zapsána do DB jako nový objekt Nástroje (http://inqooltest-arclib.libj.cas.cz/tools) a následně navázána na každý další ingest.

**Comment by ZdenekVasek** [comment]
Můj dotaz směřoval spíše na to, jakým způsobem se správce dozví o detekci nové verze DROID - viz "ARCLib aktualizaci Droidu neprovádí, pouze detekuje jeho novou verzi." To že neprobíhá automatická aktualizace je v pořádku.

**Comment by yantom** [comment]
Notifikace tohoto typu neexisutje.

**Comment by ZdenekVasek** [comment]
Jaký je tedy význam detekce novvé verze DROID? CHápal jsem to tak, že pokud detekce existuje, tak by měl být správce informován, aby zajistil aktualizaci.

**Comment by yantom** [comment]
Zde došlo k nedorozumění. Systém detekuje že Droid byl aktualizovaný, nikoliv že je dostupná aktualizace.

**Comment by ZdenekVasek** [comment]
Za aktuální situace navrhuji uzavřít. Úpravu ARCLib v tomto rozsahu nyní neprovedeme, můžeme s touto automatizací počítat do budoucího rozvoje. Pokud @godnat souhlasí.

**Comment by yantom** [comment]
Na testovacím serveru bude aktualizován DROID a otestováno že v ARCLib XML bude uvedena jeho nová verze. Následně bude issue zařazen do backlogu (požadavek na detekci možné aktualizace ARCLibem).

**Comment by yantom** [comment]
V nových verzích zapisuje DROID do výstupu příkazu i řádek s časovou značkou:

*2021-02-18T15:08:09,228  INFO [main] DroidCommandLine:140 - Starting DROID*

V nové verzi ARCLibu toto ignorujeme, uváděná verze DROIDu je pak např.:

*DROID: version: 6.5, Signature files: 1. Type: Binary Version: 91 File name: DROID_SignatureFile_V91.xml 2. Type: Container Version: 20170330 File name: container-signature-20170330.xml*

Nasazeno a otestováno na testovacím serveru.
