### ISSUE TITLE
Neuvedení kontaktu na uživatele

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#105]
Dle funkčních požadavků by systém měl "pro každého uživatele ukládá systém mail, instituci". Hlášeno průběžně na projektových schůzkách od počátku roku 2020. Zatím beze změny, proto vytvářím toho hlášení. Minimálně mail je důležitým údajem, který by měl být v systému k dispozici pro možnost jednoduchého kontaktu. Předpokládám, že mail by měl být uveden někde na úrovni jednotlivých záznamů pod https://arclib-test.lib.cas.cz/users.

**Comment by yantom** [comment]
Viz https://github.com/LIBCAS/ARCLib/issues/83

**Comment by ZdenekVasek** [comment]
Pardon. Omlouvám se.
