### ISSUE TITLE
Nedostupné workflow definitions z GUI

### ISSUE THREAD

**Issue by yantom** [LIBCAS/ARCLib#106]
Zakládám issue na základě emailu:  _Workflow definitions (bpmn soubory) nejsou dostupné ani ve frontendu ani ke stažení. Náhledy jsou prázdné, stejně tak se stahují prázdná xml. Přesto se však zdá, že tam jsou přítomny a jsou funkční, neboť Workflow definition 1 jsem dnes použil při ingestu_

Jedná se o drobnost na FE, bude opraveno.

**Comment by yantom** [comment]
Opraveno.

**Comment by jbil7** [comment]
Ověřeno, funguje. Děkuji! Z mého pohledu je možno issue uzavřít.
