### ISSUE TITLE
Chyba: Couldn't execute activity ...

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#107]
Všechny ingesty (včetně vzorového SIP balíku na wiki) padají na tuto chybu:

> couldn't execute activity <serviceTask id="ServiceTask_0b2g5c0" ...>: Premature end of file.

Posledním úspěšně zpracovaným krokem je vždy `ARCLib_metadata_extraction`.

**Comment by jbil7** [comment]
V průběhu víkendových testů jsem zjistil, že chyba se při ingestu již nevyskytuje. Byl proveden zásah ze strany Inqoolu, nebo problém odezněl sám bez zásahu?

V druhém případě (tedy nebyl-li proveden zásah ze strany Inqoolu) se domnívám, zda chyba nemohla být zapříčiněna ze strany [loc.gov](http://www.loc.gov). V NK jsme totiž měli v uplynulém týdnu obdobný problém, a sice při validaci pomocí xsd šablon pocházejících z Library of Congress. Na základě hlubších průzkumů jsme zjistili, že vliv na funkčnost šablon měly `schemaLocation` odkazy na adresy `http://www.loc.gov/mods/xml.xsd` a `http://www.loc.gov/standards/xlink/xlink.xsd`. Poté, co jsme tyto odkazy přesměrovali na tytéž dříve lokálně uložené šablony (xml.xsd a xlink.xsd), chyba se již nevyskytovala.

Byla by takováto příčina problému možná i v případě ARCLibu? Pokud ano, pak bych se chtěl zeptat, zda by veškeré odkazované xsd šablony nebylo možné umístit do filesystemu, na němž běží ARCLib, aby bezchybný běh systému nebyl závislý na dostupnosti a korektnosti schémat v jiné instituci?

**Comment by yantom** [comment]
Oprava nasazena.

**Comment by jbil7** [comment]
Moc děkuji! Bohužel mne jen nenapadá, jak toto otestovat. Chyba byla aktuální v červenci t.r. Napadají mne tedy pouze dvě možnosti:

- prohledat aktuální zdrojový kód, zda se na nějaký odkaz `schemaLocation` nezapomnělo. Aktuální zdrojový kód však momentálně na githubu není (poslední verze je z listopadu 2019).
- otestovat funkčnost systému v offline režimu. To je však spíš úkol pro admina serveru, na němž arclib běží.

**Comment by yantom** [comment]
Již je možné ověřit v zdrojovém kódu, viz https://github.com/LIBCAS/ARCLib/commit/e32fb8ed3efd86eca53c108a87fec4d131ede533#diff-daae65c21a99a7acc4e592ec8ff1fc1e2f44cf64d7fc847406a2dab7b0c3dc2f diff souboru mets.xsd

**Comment by jbil7** [comment]
Ověřeno, moc děkuji!
