### ISSUE TITLE
Nové vyhledávání AIP založené na uloženém vyhledávacím dotazu funguje jen někdy

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#108]
Při pokusu o nové vyhledávání založené na dotazu ve "Vyhledávacích dotazech" se ve většině případů správně ukáže záložka "Vyhledání AIP" a rovnou jsou nastaveny filtry tak, jak byly definovány v uloženém vyhledávacím dotazu. V některých případech (například když je uložený vyhledávací dotaz založený pouze na klíči ve formátovém registru) se ovšem nové vyhledávání s uloženými parametry nespustí a pouze se zobrazí záložka "Vyhledávání AIP", kde nejsou žádné vyhledávací dotazy předvyplněny.

**Comment by yantom** [comment]
Opraveno.

**Comment by kerschfilip** [comment]
Otestováno, funguje. Díky!
