### ISSUE TITLE
Selhání ingest workflow kvůli validačnímu profilu

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#109]
Dobrý den,

při ingestu několika balíčků se mi stalo, že ingest workflow skončilo selháním (INTERNAL_ERROR, java.lang.NullPointerException...). Problém nastal vždy při procesu validace balíčku. Použitý validační profil byl [FK_kontrola_archivniho_balicku](https://arclib-test.lib.cas.cz/validation-profiles/14c9de20-8895-11ea-bddc-d76376ed08c8), nicméně mi nepřipadá, že by v něm bylo něco špatně. Vyzkoušel jsem i rozdělit jednotlivá pravidla `<rule>` do samostatných validačních profilů a při tomto postupu balíčky prochází. Problém nastává vždy až při jejich kombinaci. 

Například zde: [Ingest workflow ARCLIB_000001455](https://arclib-test.lib.cas.cz/ingest-workflows/ARCLIB_000001455)

Díky za pomoc!

**Comment by yantom** [comment]
Chybu způsobuje následující pravidlo:

```xml
<!-- kontrola přidělení recordIdentifier source="CZ prAS" -->
  	<rule>
 		<nodeCheck>
            <filePathGlobPattern>data/mets.xml</filePathGlobPattern>
            <xPath>//recordInfo/recordIdentifier[@source="CZ PrAS"]</xPath>
          		<regex>[0-9]*</regex>
        </nodeCheck>
	</rule>
```

V mets.xml ingestovaného balíku je hodnota /recordIdentifier/@source "CZ-PrSK", tedy element z pravidla nebyl nalezen. V nové verzi systému je místo NullPointer exception vyhozena vyjímka MissingNode.

**Comment by kerschfilip** [comment]
Díky za radu, vyzkoušel jsem to v nové verzi. Systém vyhazuje výjimku "MissingNode", čímž si myslím, že je problém vyřešen. Ještě jednou díky!
