### ISSUE TITLE
Sledování procesů při ingestu

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#11]
Pro lepší odhalování a řešení chyb při ingestu by bylo vhodné zpřehlednit sledování jednotlivých procesů při ingestu, a to již od počátku uploadu. V současné době se při uploadu ukazuje v popředí tento obrazec, který dočasně (v řádu desítek sekund až jednotek minut) znemožňuje práci s prostředím:

![arc_ingest](https://user-images.githubusercontent.com/37844034/52651664-ddcefc00-2eec-11e9-9cb7-dcd31a37be25.jpg)

Jako jedno z možných provedení se nabízí řešení tzv. "kompletní průvodky" od AIP:

[kompletni_pruvodka_vzor_z_aip.pdf](https://github.com/LIBCAS/ARCLib/files/2856680/kompletni_pruvodka_vzor_z_aip.pdf)

Momentálně je možné pouze zobrazení chyby v menu "Ingest workflows", z něhož ovšem není zřejmé, jaké procesy chybě při ingestu předcházely a v které fázi se dotyčný ingest nachází.

**Comment by yantom** [comment]
Drtivou většinu času v tomto případě zabírá synchronní update balíku. Po uploadu se ještě provede pár rychlých synchroních operacích v rámci preingestu a jednotlivé kroky ingestu poté již běží asynchroně. Vzhledem k tomu že ingest skrze GUI je zamýšlen spíše pro testovací účely (v produkci budou balíky tahány v dávkách z úložiště dodavatele), nechali jsme operaci synchroní aby uživatel ihned viděl chybu která může nastat ještě před započetím ingestu (např. chybně zadaný typ hashe).

Co se týče samotného ingestu, stav zpracování lze sledovat v sekci události, kterou se chystáme společně s ostatními změnami nasadit zítra. Ukázka: https://i.imgur.com/zoEs7Dm.png O nasazení budeme informovat emailem.

**Comment by hochla-simon** [comment]
Počas uploadu po novom vypisujeme hlášku upozorňujúcu, že sa jedná iba o upload a nie samotný ingest.
