### ISSUE TITLE
Balíčky ingestované v debbuging mode se po užití forget funkce nemažou z Workspace

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#114]
Po získaném přístupu na Workspace jsem zjistil, že balíčky, u nichž proběhl úspěšný ingest v ladícím chodu a u nichž byla následně spuštěna funkce `forget` pro smazání, se z Workspace (konkrétně z adresáře `arcStorageData`) nesmažou. 

Z dokumentace mi však vyplývá, že `forget` by měl být jakýmsi ekvivalentem `Delete AIP` pro debug mode (například z formulace "Use `forget` feature instead of deletion", nebo "Clicking the button removes all debug ingests of the authorial package", obojí v kapitole `Usage@Debug Mode`). Chápu-li to správně, neměly by se balíčky ingestované v debugging mode s funkcí `forget` z Workspace smazat? Pokud mi unikla nějaká část dokumentace, pak se omlouvám.

Děkuji.

**Comment by yantom** [comment]
Nasazena oprava.

**Comment by jbil7** [comment]
Potvrzuji, že mazání při funkci forget funguje. Děkuji!
