### ISSUE TITLE
Návrh: doplnění popisu událostí v ingest workflow následujících po metadata_extraction

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#116]
Při testech si delší dobu všímám, že v popisu událostí v ingest workflow na frontendu je vždy jako poslední uveden proces `metadata_extraction`. Předpokládám však, že toto není poslední úloha při ingestu. Prosím, bylo by ještě možné do událostí doplnit i následující procesy popsané v [dokumentaci](https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow#bpm-tasks) ?

Navzdory funkčnímu logování se domnívám, že stručný přehled všech událostí na frontendu a jejich (ne)úspěšných dokončení a statusů by usnadnil diagnostiku případných chyb v systému nejen administrátorům, ale i ostatním uživatelům systému.

Taktéž bych se přimlouval za doplnění reportů nastalých incidentů, které byly nově implementovány. Viz [druhý odstavec mého komentáře](https://github.com/LIBCAS/ARCLib/issues/73#issuecomment-712939270) v issue #73 .

Předem děkuji!

**Comment by yantom** [comment]
Jedná se výpis událostí zapsaných v AIP XML. Po extrakci metadat následuje už jen generování samotného AIP XML a uložení. Událost generování můžeme zapsat jako "information package creation".  Události uložení nemohou být do XML zapsány (uložení -> zápis o uložení -> uložení -> zápis o uložení ...).

**Comment by yantom** [comment]
Nasazena nová verze ve které je přidána událost "information package creation".

**Comment by jbil7** [comment]
Děkuji! Potvrzuji, že událost se zapisuje na frontendu i do arclibxml jako premis:event. Stejně tak potvrzuji, že v událostech jsou hlášeny i další incidenty, které byly nedávno nasazeny.

Chápu důvod, jejž zmiňujete, že do AIP XML nelze zapsat událost o úspěšném uložení. Nicméně kladu si zde otázku, zda všechny položky event-listu ve frontendu musí bezpodmínečně být i v AIP XML. U eventů proběhlých před uložením bych to samozřejmě očekával a myslím, že je to správně tak, jak to je nyní. Nicméně v případě uložení se domnívám, že by mohla být zpráva o této události aspoň mezi eventy ve frontendu ingest workflows. Ponechal bych toto diskusi. V případě, že se to bude jevit jako zbytečné nebo neproveditelné, můžeme issue uzavřít.

**Comment by yantom** [comment]
Pokud se bavíme pouze o feedbacku uživateli prostřednictvím GUI, pak nositelem informace o úspěšném uložení je stejně tak změna stavu Zpracováno -> Perzistentní. Vzhledem k tomu že aktuálně jsou události spjaté s zápisem do XML navrhuji nyní neřešit a uzavřít, případně přidat do backlogu.

**Comment by yantom** [comment]
Prozatím dostačující, možné implementovat rožšíření do budoucna, viz #120
