### ISSUE TITLE
Build ze zdrojových kódů - nevalidní závislost

### ISSUE THREAD

**Issue by mduda100871** [LIBCAS/ARCLib#118]
Zdravím,

stáhl jsem poslední commit, rozbalil a pokusil se o build aplikace:

`...ARCLib$ mvn clean package -Dmaven.test.skip=true`

Maven si začal stěžovat na nedostupnou knihovnu `itext` - viz výpis:

![arclib-itext-00](https://user-images.githubusercontent.com/8750622/99546909-37643480-29b7-11eb-8e9a-ed7583cdcd39.png)

Build sice doběhl, ale nejsem si úplně jistý, zda-li je takto sestavená aplikace plně funkční, nebo jde opravdu jen o nějakou zapomenutou závislost na knihovně, která už pak není nikde využita.

Takže jsem stáhl inkriminovanou knihovnu ručně a naimportoval do svého lokálního `.m2` repozitáře. Následně opakovaný build už proběhl bez stížností.

Závěr. Pokud jde jen o zapomenutou závislost, bylo by dobré ji odstranit. Pokud je knihovna naopak využívána, ale musí se instalovat ručně, bylo by dobré to zmínit explicitně v dokumentaci.

Já knihovnu stáhl odtud:
[http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js6/](url)

a do lokálního repozitáře nainstaloval příkazem:
```
mvn install:install-file -DgroupId=com.lowagie -DartifactId=itext -Dversion=2.1.7.js6 -Dpackaging=jar -Dfile=/tmp/itext-2.1.7.js6.jar
```

MD

**Comment by yantom** [comment]
opraveno
