### ISSUE TITLE
Soubor, který je možné uložit u formátů (modul Plánování dl. ochrany) se neuloží nebo nejde najít

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#119]
V modulu Plánování dlouhodobé ochrany v části Formáty, je možnost u jednotlivých formátů nahrát soubor, ale v jednom případě se soubor asi vůbec neuloží a ve druhém asi uloží, ale nevím, kde pak je. 
V Definici formátu: https://arclib-test.lib.cas.cz/formats/147/format-definition/28d1a84d-1f1d-40ef-9f2c-1cc3ab0760a6  se neuloží vyplněný "Národní garant", "Popis plánování dlouhodobé ochrany" ani ten soubor.

Podobná obrazovka je pak pod "Aktualizovat s lokální definicí", odtud se uloží Národní garant, Popis plánování dlouhodobé ochrany a asi i soubor, ale pak se nezobrazuje.

**Comment by yantom** [comment]
Opraveno. **edit** prozatím ale nenasazeno, budu informovat

**Comment by yantom** [comment]
Nasazeno.

**Comment by godnat** [comment]
Funguje částečně. 
Nahrání souboru, uložení a jeho pozdější stažení funguje pokud ho přidávám do existující definice formátu  (u všech formátů první definice co tam je, před aktualizací). 

Pokud zvolím "Aktualizovat s lokální definicí" objeví se menu, kam je možné zapsat nové informace a nahrát soubor, ale tento soubor z nové definice, pak nelze nikde nalézt. 

Zkusila jsem to u těchto formátů: 
https://arclib-test.lib.cas.cz/formats/137
https://arclib-test.lib.cas.cz/formats/1905

Soubor jsem vložila ke všem definicím, ale dostupný je jen u té první. Podle mě by měl být dostupný u všech. 

Ještě mě napadá otázka k diskuzi- jestli tam nechceme mít možnost nahrát třeba 2 soubory.

**Comment by yantom** [comment]
Problémem je že soubory nejsou verzovatelné - nejsou tedy např. ani součástí exportu formátové definice do JSON nebo byte array. V současnosti by měl být tedy evidovaný spíše u entity formátu než jeho definice.

**Comment by godnat** [comment]
Může být podle mě provedeno, jak je v zápisu ze schůzky, resp. nenapadá mě, čemu by mohlo vadit následující řešení:
Soubor se nebude ukládat u definic (zmizí tedy i pole, kde se dá soubor vložit). 
A za mě by bylo ideální uložit víc souborů k formátu- může se tam vložit specifikace formátu, pak jeho lokálně nastavený profil (jako u JPEG2000), možná i nějaké hodnocení formátu, migrační plán apod.

**Comment by yantom** [comment]
Přeimplementujeme tak aby se soubor uchovával u entity Formátu a bylo možné uchovat více souborů k jednomu formátu.

**Comment by yantom** [comment]
Implementováno a nasazeno.

**Comment by godnat** [comment]
Funguje, děkuji.
Nyní lze nahrávat soubory, jen u entity Formát, je možné nahrát více souborů a soubory lze následně stáhnout.
