### ISSUE TITLE
Chyba: Ingest WF - nezobrazuje se aktuálně otevřený formulář

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#12]
Při otevření "Ingest workflow" se nezobrazují údaje k danému ingestu, nýbrž k ingestu, který byl otevřen naposledy, viz obrázek:

![arc_ingest_wf_chyba_prohlizece](https://user-images.githubusercontent.com/37844034/52653890-330d0c80-2ef1-11e9-9838-7b19d8637119.jpg)

Po zavření "ingest workflow" na obrázku a otevření ingestu, k němuž se patrně vztahuje nadpis, se objeví opačná situace (barevně znázorněno):

![arc_ingest_wf_chyba_prohlizece2](https://user-images.githubusercontent.com/37844034/52654115-a020a200-2ef1-11e9-9b22-6c223245c62b.jpg)

Užitý prohlížeč: Microsoft Edge 41.16299.820.0

**Comment by yantom** [comment]
Opravu této chyby se chystáme společně s ostatními změnami nasadit zítra. O nasazení budeme informovat emailem.
