### ISSUE TITLE
Nelze založit novou definici workflow

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#123]
Nedaří se mi založit novou definici workflow, vždy se vrací chyba: _500 Error java.lang.NullPointerException_

**Comment by yantom** [comment]
Toto bylo zavlečeno přidáním atributu externího id, v DB pravděpodobně
chybí sekvence pro jeho generování. Opravíme ještě dnes.

**Comment by kerschfilip** [comment]
funguje, děkuji
