### ISSUE TITLE
Chybějící tlačítko DELETE

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#125]
U _Definicí workflow_ a _Validačních profilů_ chybí u jednotlivých položek tlačítko pro jejich smazání, přestože by alespoň některé určitě smazatelné být měly - problém se vyskytuje i u nově založených a nepoužitých profilů/definicí

**Comment by yantom** [comment]
Doplněno, smazatelné jsou všechny. Jedná se o logické smazání, v DB zůstávají a při prokliku skrze link z jiné sekce, nebo přístupu přes ID jsou zobrazeny.

**Comment by kerschfilip** [comment]
funguje, děkuji
