### ISSUE TITLE
Chyba při ukládání na Archival Storage

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#128]
Dobrý den,

nedaří se mi v tuto chvíli ingestovat jakýkoliv balíček do ARCLibu, všechny ingest workflows končí chybou (přesněji vyvolají incident) při ukládání na archival storage [například tady](https://arclib-test.lib.cas.cz/ingest-batches/57d9b67b-b7a5-49f2-b496-c77f92f13dec)

Zpráva:
```
couldn't execute activity <serviceTask id="archivalStorage" ...>: ARCLib incident: Ingest workflow internal runtime exception: java.lang.ClassCastException: class java.time.Instant cannot be cast to class java.lang.Long (java.time.Instant and java.lang.Long are in module java.base of loader 'bootstrap')
```

**Comment by yantom** [comment]
Jedná se o testovací prostředí? Mohu se zeptat, zda jste přiřadil dodavatelskému profilu novou definici workflow? O nutnosti toto provést jsem informoval emailem 1.2.2021 - zasílal jsem na arclib mailman skupinu, omlouvám se pokud nejste na seznamu příjemců:

Všem používaným producentských profilům bude nutné přiřadit nový workflow definition - závěr ingestu a spolupráce s archival storage byla přepracována, z funkčního hlediska se nic podstatné nezměnilo. Nové definice byly nahrány na testovací server: kompletní - https://arclib-test.lib.cas.cz/workflow-definitions/c642de20-647e-11eb-8e13-29510e40f403 bez fixity checkeru - https://arclib-test.lib.cas.cz/workflow-definitions/51f85c20-647e-11eb-8e13-29510e40f403 . Jsou také aktualizovány na wiki.

**Comment by kerschfilip** [comment]
Ano, jedná se o testovací prostředí a při ingestu jsem použil novou kompletní definici WF, přesně tu, na kterou odkazujete. Například zde: https://arclib-test.lib.cas.cz/ingest-batches/02ad313f-c411-4527-ad61-38fbba2d60c1

**Comment by yantom** [comment]
Děkuji. Opravili jsme mnoho drobnějších chyb. Pro jistotu jsem opravu otestoval i na Vašich datech zde: https://arclib-test.lib.cas.cz/ingest-batches/c9b400b4-a54f-44a1-b147-e66c60440744 a zde: https://arclib-test.lib.cas.cz/ingest-batches/42bd2e92-7161-4a7f-bb8c-c2415c94bd0a .
 
Všiml jsem si, že ve složce pro automatickou rutinu máte prefixy PROCESSING i před .sums souborem, což by ARCLib provádět neměl, předpokládám tedy že jste takto balíčky zablokoval záměrně sám. Pokud tak dělal ARCLib, nyní tak již nedělá.

V rámci oprav jsme ještě implementovali jedno vylepšení a to že pokud se balíček v době selhání již v překladišti nenachází, systém ho ignoruje misto toho aby ho hledal za účelem nastavení prefixu FAILED a následně selhal s tím že se zde soubor nenachází.

**Comment by kerschfilip** [comment]
Děkuji, problém je vyřešený, issue zavírám.
