### ISSUE TITLE
Tlačítko "Exportovat" někdy neprovádí žádnou aktivitu

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#134]
Tlačítko "Exportovat" v okně "Hromádka" v některých případech neprovádí žádnou aktivitu (ani po označení balíčků), pouze dotyčné okno zmizí. Problém se vyskytuje nepravidelně, dle dosavadních zkušeností nejčastěji ihned po přihlášení. Většinou pomůže opětovné načtení stránky.

Testováno na prohlížečích Chromium 108.0.5359.124 a Firefox 107.0.

**Comment by yantom** [comment]
Chyba opravena, nasazeno na TEST server,

**Comment by jbil7** [comment]
Děkuji! Vyzkoušel jsem a chyba se zatím neprojevila.
