### ISSUE TITLE
Hromádka - Příkaz "Odstranit vybrané z hromádky" nefunguje v kombinaci se zaškrtnutým "Vše"

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#137]
Dobrý den,

při pokusu vyprázdnit hromádku jsem zjistil, že při zaškrtnutí políčka "Vše" nefunguje příkaz "Odstranit vybrané z hromádky" (nic se po kliknutí nestane). Musel jsem proto naklikat všechny balíčky, které mám v hromádce odložené, poté odstranění zafungovalo.

**Comment by kerschfilip** [comment]
Zdravím, také jsem narazil na to, že v dialogovém okně "Moje hromádka" nefunguje správně možnost vybrat vše. Všiml jsem si, že  po zaškrtnutí této možnosti se nezaškrtnou checkboxy v dialogovém okně, ale v okně pod ním. Možná to s výše popsaným problémem souvisí. Díky
![image](https://user-images.githubusercontent.com/57805328/212010815-d0f984cc-67d6-4936-aa79-4a7a08c65d1d.png)

**Comment by yantom** [comment]
Jednalo se o chybu, oprava je nasazena na TEST.
