### ISSUE TITLE
Chyba při vyhledávání AIP (v1.2.0)

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#141]
Po nasazení verze 1.2.0 jsme narazili na problém při vyhledávání uložených balíčků:

Postup:

  * jdu na "Vyhledávání AIP",
  * kliknu na "resetovat" (nebo tam úplně cokoliv zadám)
  * a dám "Odeslat"
  * vrátí se chyba  
    _400 Error cz.cas.lib.core.index.UnsupportedSearchParameterException: field:
    producer_id not mapped in index of: arclibXmlMainIndex_ 

chyba se projevuje i na arclib-test.lib.cas.cz

Zdá se, že problém by mohl být v oprávnění uživatelů - superadmin může vyhledávat bez problému, uživatelé s nižším oprávněním ale naráží na tuto chybu

**Comment by yantom** [comment]
V definici indexu ARCLib XML chyběl řádek, doplněno: a73e33688c4adfdb4f3202dac157520784b488f0
Návod na propagaci opravy přidán do release notes.

**Comment by mduda100871** [comment]
Zdravím,

tak mám dva poznatky:

1. stáhnul jsem aktuální zdrojáky, sestavil nový build, ale problém zůstal,
2. pokud referencuji csv externě z hlavního konfiguračního souboru, tak to funguje - použil jsem následující:
https://github.com/LIBCAS/ARCLib/blob/master/system/src/main/resources/index/arclibXmlIndexConfig.csv

`arclib.arclibXmlIndexConfig=file:/home/arclib/arclib-application/arclibXmlIndexConfig.csv`

Externí referenci bych se rád vyhnul kvůli budoucím updatům, lepší by bylo používat defaultně csv na classpath. Není tam ještě nějaký bug, kdy je csv na classpath ignorován?

Díky, MD
