### ISSUE TITLE
Na detailu AIP se zobrazují popisná metadata jiných AIPs

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#142]
Zdravím,

na obrazovce Detailu AIP se u některých AIP zobrazují i nesouvisející popisná metadata patřící patrně jiným AIP. Například zde: https://arclib-test.lib.cas.cz/aip/ARCLIB_000005180 se mají zobrazovat jen dvě poslední tabulky `DCMD_TITLE_0001` a `DCMD_VOLUME_0001`, celkem se jich ale vypisuje cca 200. 

Na produkčním nasazení v KNAV se nám tento problém projevuje jen u AIP, které byly ingestovány před nasazením v.1.2.0. U nově ingestovaných balíčků problém není.

**Comment by yantom** [comment]
Jednalo se o chybu vyhledávacího dotazu do indexu. Oprava nasazena na TEST prostředí.

**Comment by kerschfilip** [comment]
OK, díky!
