### ISSUE TITLE
sipMerger - java.lang.NullPointerException

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#146]
Ingest SIP, ve kterém oproti již uložené verzi

- je 1 soubor navíc
- je 1 soubor změněný
- 1 soubor chybí

selhává v rámci úlohy sipMerger.

Zpráva
```
couldn't execute activity <serviceTask id="sipMerger" ...>: ARCLib incident: Ingest workflow internal runtime exception: java.lang.NullPointerException
```

Ingest dávka na testovacím prostředí: 6e900f6c-2617-4bf5-87c7-6613dba8ba52

**Comment by yantom** [comment]
Chyba opravena, oprava nasazena na TEST.

**Comment by kerschfilip** [comment]
Díky, java.lang.NullPointerException je pryč, nyní se mi ale objevuje jiný problém, stále u sipMerger. Zkusil jsem vyřešit incident u původní dávky i spustit novou (523d19b2-4805-4f9e-acc5-8846dd7af182)

_couldn't execute activity <serviceTask id="sipMerger" ...>: ARCLib incident: Ingest workflow internal runtime exception: java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor_

**Comment by kerschfilip** [comment]
Problém se mi už nepodařilo reprodukovat.
