### ISSUE TITLE
Důvod odmítnutí ingestu

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#15]
Při pokusu o ingest podle návodu na GitHub vložení selhalo s chybovou hláškou "AUTHORIAL_PACKAGE_LOCKED". Tento stav není v dokumentaci popsán. Jedná se o balíček s ID ARCLIB_000000031.

**Comment by hochla-simon** [comment]
Stav AUTHORIAL_PACKAGE_LOCKED je popísaný vo Wiki dokumentácií na stránke `Ingest batches`, doplnili sme pred pár dňami: https://github.com/LIBCAS/ARCLib/wiki/Usage:-Ingest-batches#ingest-workflow-detail.

V prípade zlyhania ingestu na AUTHORIAL_PACKAGE_LOCKED  je nutné buď:
a) počkať na dokončenie predchádzajúceho ingestu daného balíka alebo
b) odstrániť vzniknutý incident (taktiež popísané na stránke `Ingest batches`)
