### ISSUE TITLE
Nova verzia DROIDu pri kazdom update signature files

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/ARCLib#18]
Chceme vytvarat novu verziu DROIDu pri kazdom update signature files? nebude tym padom zbytocna granularita verzii?

**Comment by godnat** [comment]
Je myšlena nová verze nástroje v části Plánování dlouhdobé ochrany-Nástroje http://inqooltest-arclib.libj.cas.cz/tools ? Jako je tomu u CLAMAV?

**Comment by hochla-simon** [comment]
Áno. Ako môžete vidieť, v priebehu niekoľkých dní bolo vytvorených viac než desať verzií DROIDu, nová verzia nástroja sa automaticky vytvára pri každom automatickom update signature files DROIDu.

**Comment by hochla-simon** [comment]
U CLAMAV je tomu rovnako, akurát aktualizácie prebiehajú vo väčších intervaloch, tak sa toto kumulovanie verzií neprejavuje v takej miere ako u DROIDu.

**Comment by yantom** [comment]
V pripade Droidu se jedna o bug zapricineny nevhodnou konfiguraci sluzby, kdy se stderror plnil INFO logy.

**Comment by yantom** [comment]
Naopak CLAMAV opravdu updatuje svou virovou databázi každý den: [https://lists.gt.net/clamav/virusdb/](https://lists.gt.net/clamav/virusdb/,) tedy momentálně každý nový den ve kterém se provede nějaký ingest vyvolá vytvoření nového toolu. Navrhujeme možnosti:

1) nechat tak jak je
2) vypnout automatický update virové databáze (případně nakonfigurovat periodický update v jobu OS/ARCLibu)
3) updatovat záznam v ARCLibu pouze při zjištění nové verze jádra CLAMAV (jádro je třeba vždy aktualizovat manuálně)

ještě dodám že pokud je jádro zastaralé, program freshclam, který je zodpovědný za update virové databáze vypíše warning, i s touto informací by se dalo nějak naložit

**Comment by godnat** [comment]
V soupisu nástrojů preservation planning určitě nechcem záznam pro každou aktualizaci virové databáze nástroje CLAMAV, tam by stačila jen informace o tom, že je využíván nástroj CLAMAV a případně jeho vrcholová verze (záleží jak často ta se mění). Vhledem k tomu, že to není nástroj pro preservation planning, tak záznam by tam měl být max při nějaké zásadnější změne nástroje. 

V metadatech v ArclibXML by pak ale měla být informace přesnější s udáním konkrétní verze antiviru. 

Takže nástroj se může aktualizovat tak jako teď, ale v preservation planning nebude vznikat záznam pro každou aktualizaci (jen pro nějakou zásadnější), ale v metadatech by ta informace byla podrobnější--půjde to takto?

**Comment by hochla-simon** [comment]
Vyriešené nasledovne:
1. V metadátach ArclibXml v elemente **premis:eventDetail** sa náchadza "dlhá" verzia antivírového nástroja, obsahuje aj vírusovú databázu použitú u daného ingestu: `ClamAV 0.99.2/23871/Mon Sep 25 10:44:09 2017`.

2. V sekcí nástroje v Preservation planning a v elemente **premis:agent/premis:agentNote** ArclibXml sa nachádza "krátka" verzia antivírového nástroja: `ClamAV 0.99.2`. V súpise nástrojov sa teda vytvára nová verzia nástroja iba pri zásadnejšej zmene vo vnútri ClamAV.
