### ISSUE TITLE
V jakých polích ArclibXML probíhá vyhledávání v "Vyhledávání AIP"

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#19]
Z jakých polí v ArclibXML se vytvářejí indexy, které se pak prohledávají pomocí různých polí ve "Vyhledávání AIP"?  
Příklad: pole "Jméno vytvářející aplikace"  se může brát z ARCLIB:creatingApplicationName ze sekce ARCLIB_001 nebo z ARCLib:creatingApplicationName ze sekce ARCLIB_005.

Zkoušíme teď různé úpravy výsledné podoby ArclibXML v Sip profilech v XSL transformaci a zajímá nás jak tyto úpravy mohou ovlivnit, případně rozbít vyhledávání--tj. co bychom tedy určitě neměli měnit.

Případně, zda máme my jako uživatelé pak možnost ovlivnit nejen XSL transformaci v Sip profilech ale i v jakých polích se bude vyhledávat (například změnu kdy pole "Sériové číslo modelu skeneru" nebude vyhledavat v serialNumber v sekci ARCLIB_005, ale v serialNumber v sekci ARCLIB_004 apod.)

**Comment by yantom** [comment]
Soupis indexovaných položek je součástí analytického dokumentu zde: [https://docs.google.com/spreadsheets/d/1OR_NyrTfajZo5emu4PV2c0-pA3D6s2E6lcyx2cJXzLU/edit#gid=586517350](https://docs.google.com/spreadsheets/d/1OR_NyrTfajZo5emu4PV2c0-pA3D6s2E6lcyx2cJXzLU/edit#gid=586517350), který zároveň slouží jako zdrojový soubor pro aplikaci. Indexované jsou pouze položky které mají vyplněn alespoň jeden z posledních dvou sloupců. Popis v prvním sloupci odpovídá sekci v GUI, v druhém sloupci je XPATH k elementu v ARCLib XML.

Všechny filtry vyplněné skrze formulář jsou v současnosti složeny do logického součinu (AND). Výsledkem je vždy sada dokumentů, které odpovádají tomuto složenému filtru. 

V případě že chcete vyhledávat dle *sériového čísla modelu skeneru* pouze v dokumentu ARCLIB_004 je třeba kromě filtru na sériové číslo doplnit filtr *XML ID* = `ARCLIB_004`. Výsledek bude buď prázdný nebo bude obsahovat 1 záznam: ARCLIB_004, pokud obsahoval element s zadaným sériovým číslem modelu skeneru.

Další příklady:
1) Zakladní vyhledávání 
1.1) Formulář ponecháte prázdný, prohledává se ve všech dokumentech (ARCLIB_001, ARCLIB_002, ARCLIB_xxx). Výsledkem jsou všechny dokumenty.
1.2) Vyplníte Číslo XML verze >=2. Výsledkem jsou pouze dokumenty, které vznikly při update XML verze.
1.3) Vyplníte navíc AIP ID = 4b66655a-819a-474f-8203-6c432815df1f, výsledkem jsou pouze nepůvodní XML verze konkrétního AIPu.
1.4) Odmažete filtr na číslo verze XML, výsledkem jsou všechny verze konkrétního AIPu.

2) Popisná metadata
2.1) *Specifikátor* ponecháte prázdný a vyplníte *Dublin Core* hodnotou `periodicalitem`, Výsledkem jsou všechny dokumenty jenž obsahují slovo periodicalitem v jakémkoliv DC elementu.
2.2) Do *Specifikátoru* vložíte hodnotu `DCMD_ISSUE_0001` (z atributu dmdsec@id). Výsledkem jsou všechny dokumenty jenž obsahují slovo periodicalitem v jakémkoliv DC elementu, který je zanořen v dmdsec elementu s příslušným ID.
2.3) Po změně specifikátoru na `DCMD_VOLUME_0001` je výsledek prázdný, neboť tento element neobsahuje DC typ periodicalitem, nýbrž `periodicalvolume`.

3) Ostatní filtry vnořeného indexování
3.1) V sekci *Technická metadata agregovaná přebíraná* vyplníte *Formát souboru* = `image/jp2` a *Počet souborů* >= `10`, výsledkem jsou všechny dokumenty jejichž SIP obsahoval více než 10 souborů formátu jp2.

**Comment by rudky4** [comment]
Více info: https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow

**Comment by yantom** [comment]
Zdokumentováno: https://github.com/LIBCAS/ARCLib/wiki/Usage@AIP-search
