### ISSUE TITLE
Nelze kopírovat hodnoty z obrazovky

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#2]
Například při zobrazení záznamu balíčku nelze vybrat a kopírovat text z polí. Je to drobnost, ale pro reálný provoz se určitě hodí. 

http://inqooltest-arclib.libj.cas.cz/aip/ARCLIB_000000004

![obrazek](https://user-images.githubusercontent.com/22765973/51439836-1b5eb180-1cc0-11e9-9033-f6774af488de.png)

**Comment by vjirousek** [comment]
Problém se vyskytuje zřejmě jen ve Firefox, konkrétně zjištěno u Firefox 60.4.0 ESR (64-bit). V Explorer, Edge i Chrome je označení textu a kopírování funkční.

**Comment by pavlaskovae** [comment]
V Internet Explorer 11 v některých případech po pokusu o kopírování dojde zatuhnutí rozhraní - veškeré odkazy přestanou reagovat. Je nutné prohlížeč zapnout a vypnout.

**Comment by ZdenekVasek** [comment]
Kopírování v IE 11 je funkční, ale ve 100% pokusů způsobuje zatuhnutí rozhraní.

**Comment by hochla-simon** [comment]
Preferovali by sme cestu podporovať iba moderné prehliadače (Chrome, Firefox, Edge) vzhľadom na to, že Arclib je zameraný na pomerne úzku skupinu užívateľov. Vyhneme sa tak aj ďalším problémom v budúcnosti.

**Comment by hochla-simon** [comment]
Otestované v Firefox 64.0 (64-bit), Chrome 72.0.3626.109 a Microsoft Edge 42.17134, vo všetkých prípadoch kopírovanie funguje.

**Comment by vjirousek** [comment]
Potvrzuji, ve Firefox, Chrome i Edge vše funkční. 
Podporu či nepodporu IE bychom si měli asi domluvit na projektové schůzce.

**Comment by rudky4** [comment]
Dle dohody bez podpory IE, ostatní prohlížeče budou podporovaný.
