### ISSUE TITLE
Nefunkční ingesty a náhledy do ingest-workflows

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#22]
V posledním týdnu nefunguje ingest PSP balíků, stejně tak ani náhled do ingest-workflows. 

Zadaný ingest je viditelný v Ingest batches se stavem "Processing", po jeho rozkliknutí je v ingest-workflows viditelný status "New", na němž ingest stojí. Při kliknutí na daný ingest-workflow se nezobrazí ten správný - viz příklad ingestu z 30. 3. 2019 - nýbrž jiný, z 12. 3. 2019.

Předem děkuji za vyřešení či objasnění problému.

**Comment by yantom** [comment]
Dobrý den, při nasazování nové verze jsme omylem resetovali sekvenci externích ID a proto nové ingesty kolidovaly s těmi starými. Problém je již **vyřešen**.

**Comment by jbil7** [comment]
Děkuji!
