### ISSUE TITLE
Nelze zrušit ingest v Ingest batches

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#23]
Dobrý den, při pokusu o zrušení ingestu v nabídce "Ingest batches" dojde k chybě:

> 502 Proxy error

Předem Vám děkuji za vyřešení!

**Comment by yantom** [comment]
Dobrý den, problém by se již neměl opakovat. Byl zřejmě způsoben kolizemi ingestů z předešlého issue https://github.com/LIBCAS/ARCLib/issues/22 . Po restartu služby dané ingesty doběhly do koncového stavu.
