### ISSUE TITLE
Nefungují přihlašovací údaje

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#24]
Dobrý den,

zřejmě po nasazení nové verze nefunguje přihlašování uživatelů. Nefunguje např. arc-bob, ani další vytvořené uživatelské účty.

**Comment by hochla-simon** [comment]
Dobrý deň,
prosíme o opätovný pokus o prihlásenie, na našej strane neregistrujeme problém.

**Comment by godnat** [comment]
Díky za zprávu, prihlaseni skutecne funguje. 
Byla jsem na jiné instanci Arclib (http://arclib.inqool.cz).
