### ISSUE TITLE
Chyba při ingestu: 404 null

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#26]
Při ingestu dochází k chybě s hláškou `404 null`. Použit byl SIP profile 1 (původní od inqoolu), validation profile 5 (kontrolující pouze přítomnost info.xml) a wf definition 1 (taktéž původní od inqoolu).

Předem děkuji za vyřešení!

**Comment by hochla-simon** [comment]
V rámci hotfixu bola do systému zavedená chyba spôsobujúca pád vo finálnej časti Ingestu u niektorých balíkov. Chyba bola odstránená a nové ingesty už prechádzajú úspešne.
