### ISSUE TITLE
Chyba při stahování XML a AIP

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#27]
Dobrý den,

při stahování ArcLibXML dojde k chybě (viz obrázek). Stejná chyba se objeví při pokusu o stažení AIP.

![arc_xml_cannot_be_downloaded](https://user-images.githubusercontent.com/37844034/56901401-6561eb00-6a98-11e9-8fc2-acd62ba3f0ed.jpg)

Předem děkuji za vyřešení!

**Comment by hochla-simon** [comment]
Pri nasadzovaní novej verzie archival storage sme nechtiac odmazali časť údajov z databáze, samotné dáta (t.j. obsah SIP balíkov a ArclibXml) ale na archival storage uložené sú. U nových ingestov sa táto chyba neobjavuje.

Na základe tejto udalosti sme sa rozhodli pre implementáciu služby pre záchranu databázových dát z obsahu AIP balíkov na jednom spomedzi perzistentých úložísk. Po dokončení implementácie staré dáta na archival storage obnovíme.

**Comment by hochla-simon** [comment]
Dáta na archival storage boli obnovené. Zároveň sme implementovali spomínanú službu, ktorá zaistí zotavenie sa zo situácie, keď dôjde na archival storage k nechcenému zmazaniu dát v databáze.
