### ISSUE TITLE
Chyba při ingestu: "404 null" přetrvává

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#28]
Bohužel chyba nadále u některých ingestů přetrvává. Zatímco ingest balíku ARCLIB_000000103 
proběhl v pořádku, ingesty balíků ARCLIB_000000104 a ARCLIB_000000102 selhaly opět na chybě 404 null. 
Nutno dodat, že v minulosti (např. v březnu t.r.) tyto samé balíky bez problému ingestem prošly. Prosím o analýzu problému a jeho vyřešení.

Předem děkuji!

**Comment by hochla-simon** [comment]
Priamo súvisí s chybou https://github.com/LIBCAS/ARCLib/issues/27. 

Podrobnejšie vysvetlenie problému:
Balíky ARCLIB_000000102 a ARCLIB_000000104 sa nachádzajú v stave PROCESSED, takže došlo k ich úspešnému spracovaniu Arclibom, ale neboli uložené na Archival storage (vtedy by boli v stave PERSISTED). Vzhľadom na to, že sa jednalo o násobný ingest už pred tým ingestovaných balíkov, došlo ku verzovaniu. `404 null` je hláška z archival storage, ktorá vznikla z dôvodu, že predchádzajúca verzia balíku nebola nájdená.
