### ISSUE TITLE
Nemožnost mazání/editace SIP profilu

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#29]
Jakmile se SIP profil jednou použije v Producer profilu, nelze jej poté editovat ani mazat a to i přesto, že již užíván není. Testováno z role super-admina. 

Bylo by, prosím, možné editovat a mazat SIP profily alespoň poté, co nejsou používány ani jedním z Producer profilů? Dle dokumentace by zásahy do SIP profilů měly být možné z role super-admina. 

K čemu slouží zaškrtávací pole "editable" u SIP profilu? V dokumentaci se o něm nic nenachází.

Předem děkuji!

**Comment by hochla-simon** [comment]
Ospravedlňujeme sa za chýbajúcu wiki dokumentáciu, popis atribútu `editable` bol doplnený: https://github.com/LIBCAS/ARCLib/wiki/Usage:-Sip-profiles.

Vzhľadom na návrh https://docs.google.com/document/d/1RCdW2wiG9vE2g4Bt8EY-3tJ_C__cMUOWz72F4XXAd1c/edit?usp=sharing určený k diskusii
sme sa rozhodli zamedziť možnosť následnej editácie SIP profilu v momente jeho použitia v profile producenta s atribútom **debugging mode** rovným `false`. V produkčnom prostredí by podoba SIP profilu nemala byť upravovaná, aby bola dohľadateľná presná konfigurácia podľa ktorej prebehli jednotlivé ingesty používajúce daný SIP profil.

V prípade nutnosti zmeny existujúceho SIP profilu (už použitého v produkčnom prostredí) je nutné vytvoriť nový SIP profil.

**Comment by jbil7** [comment]
Děkuji za doplnění popisu atributu `editable`. 

Na základě Vámi zmíněných důvodů považuji uzamknutí SIP profilu za opodstatněné. Z dokumentace však není zcela zřejmé, zda se jedná o chybu či o vlastnost. Proto by bylo vhodné do popisu SIP profilu doplnit informaci o uzamknutí a o nemožnosti následného přepnutí `editable` na `true`, možná i s udáním důvodu a s odkazem na použití debugging mode. Děkuji!

**Comment by hochla-simon** [comment]
Ďakujeme za spätnú väzbu, doplnili sme teda do Wiki dokumentácie aj podrobné vysvetlenie dôvodu pre uzamykanie SIP profilu v momente jeho použitia v produkčnom prostredí. https://github.com/LIBCAS/ARCLib/wiki/Usage:-Sip-profiles

**Comment by jbil7** [comment]
Děkuji za doplnění!
