### ISSUE TITLE
Uspořádání formuláře pro vyhledávání AIP

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#3]
V současné podobě je formulář pro vyhledávání AIP poměrně nepřehledný. Domnívám se, že by mělo dojít k jeho úpravě tak, aby se základní pole vešla na jednu běžnou obrazovku a další skupiny metadat by se rozbalovaly až v případě potřeby. 

V současné podobě si například umím představit defaultně sbalené tyto skupiny polí:

- Technická metadata agregovaná přebíraná
- Technická metadata agregovaná generovaná ARCLib
- Provenance a kontroly při ingestu
- Provenance přebrané ze SIP
- Provenance při aktualizaci AIP metadata
- Provenance při revalidaci novým profilem nebo opakováné identifikaci formátů v SIP

Návrh je určen k diskusi.

**Comment by pavlaskovae** [comment]
Souhlasím. Velkou pomocí by byla i možnost vymazat údaje ve formuláři. V množství polí se snadno přehlédne vyplněná hodnota.
**Edit:** Přehlédla jsem tlačítko resetovat. Možná by stálo za to ho zvýraznit.

**Comment by hochla-simon** [comment]
Uvedené skupiny polí boli implementované ako zbaľovacie, tlačítko resetovať bolo zvýraznené. Uvítali by sme otvoriť otázku dizajnu vyhľadávacieho formulára na spoločnej diskusií.

**Comment by rudky4** [comment]
Aktuálně bude upravena pozice tlačítek. 
Další optimalizace bude řešena v samostatných issues.
