### ISSUE TITLE
Účty

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#30]
Dobrý den,

 aktuálně už několik dní nefungují přístupové údaje do ARCLib pro účet arc-bob a další všeobecné testovací účty. podle zprávy kolegů z Nk nefunguje přístup ani přes nově vytvořené osobní účty. Při pokusu o přihlášení hlásí systém, že nemáme správné přihlašovací údaje.

**Comment by rudky4** [comment]
Dobrý deň,

ďakujeme za reportovanie a ospravedlňujeme sa za nedostupnosť. **Prístupy by mali byť už funkčné.**
V budúcnosti môžete upozorniť na nedostupnosť kľudne okamžite, aby sme problém opravili čo najskôr.
