### ISSUE TITLE
Ošetření bílého znaku při vkládání hash value (ingest)

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#32]
Obsahuje-li hash na konci řetězce bílý znak, např. mezeru, systém jej považuje za neplatný. Prosím, bylo by možné při vstupu ošetřit přítomnost bílých znaků na začátku a konci hashe? Děkuji.

**Comment by hochla-simon** [comment]
Ďakujeme za spätnú väzbu, biele znaky na začiatku a konci hashe ošetríme.

**Comment by jbil7** [comment]
Vyřešeno.
