### ISSUE TITLE
Viditelnost "Deletion request" z pozice zadavatele

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#33]
Deletion request je viditelný pouze z pozice potvrzovatelů, zadavatel jej nevidí. Prosím, bylo by možné žádosti o smazání AIP zviditelnit pro zadavatele, případně i pro další uživatele a ne-možnost potvrzení smazání vyřešit jejím odemknutím či uzamknutím (tak jako je nově editable u SIP profilů)?

**Comment by hochla-simon** [comment]
Súhlasíme s uvedeným návrhom až na jeden detail. Žiadosti o zmazanie balíka by mali byť viditeľné iba pre  užívateľov spadajúcich pod rovnakého dodávateľa ako má navrhovateľ zmazania balíku a nie pre všetkých užívateľov ARCLibu, aby nedošlo ku nechcenému zverejneniu IDčiek cudzích balíkov. Zmeny zapracujeme.

**Comment by jbil7** [comment]
Viditelnost žádosti o smazání z pozice žadatele je již vyřešena. 

Dodatečně mne v této souvislosti ještě napadlo, že by z pozice zadavatele mohla být užitečná i možnost zrušení žádosti - v případě, že by například došlo k omylu a zažádal o smazání dokumentu nechtěně. 

Ponechávám tento návrh diskusi.

**Comment by yantom** [comment]
Implementováno a nasazeno.

**Comment by jbil7** [comment]
Potvrzuji, že funguje a uzavírám. Děkuji!
