### ISSUE TITLE
Problém s ingestem jiné názvové konvence

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#36]
V rámci testování ingestu bylo zjištěno, že aplikace očekává pouze adresáře PSP balíků s názvy amdsec, txt, alto, usercopy a mastercopy. Upraví-li se validační profil a sip profil například na příjem balíků starších verzí s názvem adresáře "amdSec" (NDK specifikace v. 1.5. pro periodika a nižší), dojde k následující chybě: 

> couldn't execute activity <serviceTask id="ServiceTask_0fxsc9x" ...>: The file or directory file:////opt/arclib/workspace/ARCLIB_000000039/d9eda930-1cd1-11e2-bec6-005056827e51//amdsec does not exist

Z testu je patrné, že validační proces byl úspěšný a že došlo i k úspěšnému načtení metadat z hlavního metadatového souboru mets. K chybě došlo až po těchto krocích. Vzhledem k tomu, že názvová konvence PSP balíků podstupovala v průběhu vývoje definic metadatových formátů NDK drobné změny (typu amdSec a amdsec), ArcLib by měl být v tomto ohledu konfigurovatelný, nikoli fixovaný na jediné konkrétní hodnoty.

**Comment by yantom** [comment]
Problém je v SIP profilu: na řádku 18 je hodnota proměnné nastavena na "amdsec". Dle hodnoty proměnné jsou pak hledány metadatové soubory z nichž jsou extrahovány data. V současné chvíli je tedy řešením vytvoření samostatného SIP profilu pro NDK verze <= 1.5.

Pokud to bude vyžadováno, můžeme rozšířit XSLT procesor o metodu na test existence adresáře a následně dle ní správně nastavit proměnnou.

**Comment by jbil7** [comment]
Rozšíření XSLT procesoru by mohlo být jednou možností. Pak by se myslím nabízela ještě druhá možnost, a sice že v METS souboru se nacházejí `href` s relativní cestou na jednotlivé amd_metsy (XPath: `//mets:fileGrp[@ID="TECHMDGRP"]/mets:file/mets:FLocat/@xlink:href`) které by mohly být pro tento případ také využity. V NDK balíku, jehož se tento SIP profil týká, jsou tyto odkazy povinné. Pak by v XSLT ani nemusela být užita metoda na test existence adresáře.

**Comment by yantom** [comment]
Děkujeme za nasměrování. Máme pravidlo pro výběr AMDSEC souborů upravit v současném profilu používaném pro testování: *Sip profile - test JB* ?

**Comment by yantom** [comment]
Na schůzi bylo nahlášeno že nový SIP profil selhává na stylesheet kompilaci. Problém byl opraven, prosím vyzkoušejte opravu nového SIP profilu: http://inqooltest-arclib.libj.cas.cz/sip-profiles/795dadd0-1db5-11ea-b9c2-d7370bc65d5c na starší NDK specifikaci. Na novější bylo námi ověřeno v dávce http://inqooltest-arclib.libj.cas.cz/ingest-batches/1f7a5b0b-31ed-4a0e-a3ef-357980576b0e

**Comment by jbil7** [comment]
Děkuji, problém vyřešen.
