### ISSUE TITLE
Ve Vyhledávání AIP chybí u některých polí možnost "contains"

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#37]
Při vyhledávání AIP jsou u některých polí (např. u Authorial ID, Producer name atd.) k dispozici pouze možnosti "equal" a "not equal". Prosím, bylo by možné do těchto polí přidat také "contains"?

**Comment by yantom** [comment]
bude doplněno v nové verzi

**Comment by jbil7** [comment]
Vyřešeno.
