### ISSUE TITLE
Dokument importovaný pomocí Ingest routine nelze smazat

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#38]
Při dávkovém importování pomocí Ingest routine v ladícím chodu a následném mazání dokumentů příkazem `forget` byla zjištěna tato chyba:

> org.postgresql.util.PSQLException: ERROR: update or delete on table "arclib_ingest_workflow" violates foreign key constraint "related_ingest_workflow_fk" on table "arclib_ingest_workflow"
Detail: Key (id)=(e3663209-593e-4978-9240-e3f84a4b8216) is still referenced from table "arclib_ingest_workflow".

ID dotyčného balíku je `ARCLIB_000000150`.

Co může být příčinou? Je možné, že je to zapříčiněno dávkami, které jsem v ingest routine nestihl stopnout a následně skončily v chybě? Ostatní balíky z dotyčné dávky jsem smazal bez problému, chyba nastala až u posledního. Děkuji.

**Comment by yantom** [comment]
Děkujeme za nahlášení. Jedná se o úplně nezávislou chybu funkcionality zapomenutí.

**Comment by jbil7** [comment]
Opraveno, děkuji.
