### ISSUE TITLE
Návrh k ingest routine: Fronta procesů jako alternativa CRONu ?

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#39]
Rád bych zde otevřel diskusi o tom, zda je CRON vhodný jako jediný způsob časování při typu importu `ingest routine`. 

**Důvod**: Importované dokumenty totiž nemají vždy stejnou velikost, v některých případech se objem SIP balíků i několikanásobně liší (v rozmezí od 10 MB až do 10 GB). Při větším množství SIP balíků by tudíž bylo velmi obtížné hlídat velikost SIP balíků, třídit je a zvlášť nastavovat CRON tak, aby na jedné straně nenastávaly neefektivní prodlevy a na druhé straně, aby nedocházelo k přetížení na vstupu.

Aniž bych byl pro úplné vyřazení metody CRONu (může být ponechána jako manuální alternativa), přimlouval bych se k automatizování dávkových procesů. **Řešením** by mohla být automatická fronta, v níž bude k importu a zpracování paralelně připuštěn pouze určitý počet SIP balíků. Jakmile jeden ingest doběhne, může začít další ingest, zatímco u většího dokumentu může paralelně ještě ingest dobíhat. Tato metoda by měla být oproti CRONu preferována.

Bylo by takové řešení reálné?

**Comment by yantom** [comment]
Ponecháváme k diskuzi. Prozatím navrhujeme kolize v případě CRON rutin řešit tak, že v rámci rutiny nebude startována nová dávka, pokud ještě nedoběhla původní dávka.

**Comment by yantom** [comment]
V nejnovější verzi je možné na úrovni aplikace zapnout funkcionalitu zmíněnou v předchozím komentáři. Jedná se o property _arclib.skipRoutineIfPreviousBatchProcessing_

**Comment by yantom** [comment]
Dnes byla na schůzi dohodnuta implementace automatické fronty. Bude řešeno rozšířením rutin o možnost zaškrtnutí pole *automatická fronta*. Těmto rutinám bude CRON přednastaven na defaultní hodnotu, např. každou minutu (necháváme k diskuzi zda uživatelům umožnit ji upravovat). Rutina začne zpracovávat pouze balíčky se suffixem COMPLETED (prosím o potvrzení že se jedná o suffix). ARCLib zajistí že CRON při příštím spuštení nezačne zpracovávat již zpracovávané balíky (jedno z možných řešení je přepsání suffixu v překladišti na PROCESSING). V případě chyby bude suffix přepsán na FAILED.

**Comment by yantom** [comment]
@jbil7 Prosím o upřesnění:

Má se jednat o prefix nebo suffix? Zaevidoval jsem jako suffix ale nejsem si jist správností, např. zde: https://github.com/LIBCAS/ARCLib/issues/73#issuecomment-642563042 zmiňujete prefix.

Dále prosím o potvrzení že rozumíme požadavku resp. jsme ho přepsali žádoucím způsobem:

Pokud uživatel u dané rutiny nenastaví že se jedná o automatickou frontu, s prefixy/suffixy se nepracuje, v opačném případě:

1 Vkládající systém zajistí přejmenování dokopírovaných souborů prefixem/suffixem COMPLETED
2 ARCLib začne zpracovávat pouze balíčky s prefixem/suffixem COMPLETED
3 ARCLib označí balíčky které zpracovává prefixem/suffixem PROCESSING
4 Při chybě označí ARCLib balíček prefixem/suffixem FAILED a ponechá v překladišti
5 Při úspěchu označí ARCLib balíček prefixem/suffixem ARCHIVED a dle současné property konfigurovatelné na úrovní celého systému buď ponechá v překladišti nebo smaže

**Comment by jbil7** [comment]
Co se týče prefixu či suffixu, osobně bych se přikláněl k prefixu oddělenému od zbytku názvu podtržítkem, jestliže toto řešení považujete za technicky správné a reálné.

Zpracování fronty tak, jak jste jej popsal, dle mého názoru odpovídá požadavku. Chápu správně, že "vkládajícím systémem" v bodě č. 1 máte na mysli jiný systém než ARCLib, který bude balíčky do importní složky kopírovat, že ano? Aby se zamezilo nechtěnému ingestu nekompletních souboru, u přejmenování na COMPLETED by pak bylo myslím vhodné do dokumentace upozornit, že k němu má dojít opravdu až po dokopírování, nebo případně doporučit užití nějakého prefixu pro kopírující se soubory (např. PENDING).

**Comment by yantom** [comment]
Implementováno a nasazeno, popsáno ve wiki: https://github.com/LIBCAS/ARCLib/wiki/Usage@Ingest-routines#auto-flag

**Comment by kerschfilip** [comment]
@jbil7 můžeme issue zavřít? Implementace je popsaná na wiki a podle mě funguje dobře. Díky!

**Comment by jbil7** [comment]
Ano, myslím, že můžeme uzavřít.
