### ISSUE TITLE
Vyhledávání - výběr z hodnot

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#4]
U polí, jejichž hodnota může nabývat omezeného počtu známých hodnot (např. PROCESSED, PERSISTED, REMOVED, DELETED u pole "State/Stav") by bylo praktičtější řešit vyhledávání výběrem z těchto hodnot.

**Comment by hochla-simon** [comment]
Atribúty "State/Stav" a "Event type/Typ události" v kategórií "Provenance extracted from SIP/Provenance přebrané ze SIP" sme implementovali ako výber hodnôt. Po prípadnej diskusii možno použiť výčtové typy aj na ďalších miestach.

**Comment by vjirousek** [comment]
Dobře, zatím díky. Počítám že další požadavky by mohly vzejít z důkladnějšho otestování vyhledávání, jakmile se podaří nahrát větší vzorek dat.
