### ISSUE TITLE
Problémy s Ingest Workflow po nasazení verze 0.3.

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#42]
Po nasazení nové verze se při rozkliknutí "Ingest workflow" v "Ingest batches" neustále proměňuje (obnovuje) obsah stránky; střídavě se zobrazují navzájem nesouvisející ingesty, např. `Ingest workflow ARCLIB_000000164` a část `Ingest workflow ARCLIB_000000160`.

Chybné zobrazení:

![Ingest_wf](https://user-images.githubusercontent.com/37844034/69032349-89592f80-09dc-11ea-9425-7669dd1aef14.jpg)

Očekávané zobrazení:

![Ingest_wf2](https://user-images.githubusercontent.com/37844034/69032366-924a0100-09dc-11ea-86da-09c5d35e1a45.jpg)

V momentě, kdy je zobrazena chybná verze, odkazují i další volby (např. "Switch to AIP detail") na nesprávné objekty.

**Comment by yantom** [comment]
Bug se nám nepodařilo zreprodukovat ale nalezli jsme možnou příčinu. Oprava byla nasazena. V případě že se bug znovu objeví prosím založte novou issue a idálně ponechte problémová data ve stavu v jakém se nacházely při výskytu bugu (v tomto případě byly nejspíš smazány skrze funkci **Forget**)
