### ISSUE TITLE
Producer Profiles jen pro super admina? 

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#43]
Při testování jsem narazil na věc, která mi není úplně jasná - V roli admina nejde vytvářet nebo editovat Producer profiles - ani zapnout debugging mode

![image](https://user-images.githubusercontent.com/57805328/69862792-8a6f4400-129b-11ea-80ba-28a1b0135b67.png)

V roli super admina vše funguje v pořádku, ovšem podle dokumentace jsem si myslel, že možnost vytvářet a editovat profily má mít i "běžný" admin. 

pochopil jsem to špatně, nebo se jedná o chybu?

Děkuji

**Comment by yantom** [comment]
Jedná se o chybu, děkujeme za nahlášení.

**Comment by yantom** [comment]
Opraveno v aktuální verzi.
