### ISSUE TITLE
Konfigurace workflow - ingest vs. profil dodavatele

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#44]
Dobrý den 

Při ingestu SIP, ve kterém chybí jeden soubor jsem zkoušel různá nastavení workflow config. 

Ingest selhal (chyba: _processFailure : FILE_MISSING..._) v případě, kdy ve workflow config v profilu dodavatele (test_FK) bylo následující nastavení:
`[...]  
"fixityCheck": [
    {
      "continueOnMissingFiles": false,
      "continueOnUnsupportedChecksumType": false,
      "continueOnInvalidChecksums": false
    }
[...] `
a při ingestu bylo nastaveno:
`{
  "fixityCheck": [
    {
      "continueOnMissingFiles": true
    }
  ]
}`

měl jsem za to, že konfigurace nastavená v ingestu má přednost před tou v profilu dodavatele. V dokumentaci se píše:
> [...] If there are two equally named attributes the batch config has the priority over the producer config.

Je možné že jde o chybu a systém upřednostňuje profil dodavatele? Nebo chápu funkci špatně? 🙃
Jednalo se o _Ingest workflow ARCLIB_000000228_ batchID: _bff33618-bd29-42b1-b9ed-6945d82be3ea_

Podobný problém nastal při ingestu, kde jsem v profilu producenta nespecifikoval nic ohledně `"fixityCheck"`. V rámci ingestu bylo nastaveno workflow config jako `"continueOnMissingFiles": false` Místo selhání ingestu ale došlo k přerušení ingestu a vytvoření incidentu.
V tomto případě šlo o _Ingest workflow ARCLIB_000000227_ batchID: _065f0058-8e10-4fb2-92d1-e1b4a8ffd092_
Mám z toho trochu pocit, jakoby moc nezáleželo na tom, co je nastaveno v rámci ingestu a ArcLib hledí vždy jen na nastavení v profilu dodavatele

Díky za pomoc!

**Comment by yantom** [comment]
Jedná se o chybu, děkujeme za nahlášení. Opravu nasadíme do konce týdne.

**Comment by yantom** [comment]
Oprava byla nasazena na server. Po novu jsou v konfiguraci veškeré pole nahrazeny objekty - úprava byla propagována do všech existujicích rutin a producentských profilů. Upraveny byly i relevantní sekce wiki, především https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow a https://github.com/LIBCAS/ARCLib/wiki/Instructions-for-sample-ingest . Do sekce https://github.com/LIBCAS/ARCLib/wiki/Usage:-Ingest-batches byl přidán odstavec který navádí jak řešit incidenty (přepsáním celého konfigu, ne pouze konfigu pro task vyvolávající incident).

**Comment by kerschfilip** [comment]
Vše funguje, jak má. Díky!
