### ISSUE TITLE
chyby při editaci AIP XML

### ISSUE THREAD

**Issue by yantom** [LIBCAS/ARCLib#46]
Nahlášeno na schůzi. Potvrzujeme možné chybové scénáře, vyžaduje další investigaci.

**Comment by ZdenekVasek** [comment]
Stále trvá nemožnost uložit editaci XML přes webové rozhraní. Konkrétní příklad např. u této entity z účtu vasek.
![Screenshot_2020-01-26 ARCLib(1)](https://user-images.githubusercontent.com/26565876/73138399-7ad56700-4062-11ea-9cfc-d2164e816210.png)

**Comment by yantom** [comment]
Chyba byla důsledkem jiné chyby která byla již dříve opravena a oprava nasazena, přičemž jsme ale nepromazávali obsah úložiště a balík tedy zůstal poznačen touto chybou. Samotnou editaci AIP XML jsme důkladně zrevidovali, problém by se na nových balících již neměl vyskytovat.

**Comment by ZdenekVasek** [comment]
Editace funguje. Lze uzavřít.
