### ISSUE TITLE
Vyhledávací dotaz nelze uložit

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#47]
Při testování vyhledávání AIP jsem narazil na problém s uložením dotazu. Do záložky "Vyhledávací dotazy" se uloží jen název, datum a čas upravení. Není možné zobrazit výsledky vyhledávání (okno se zobrazí, ale je prázdné), stejně tak není možné provést nové vyhledávání založené na dotazu - v tomto případě se prostě jen zobrazí formulář Vyhledávání AIP. 

Menší problém může také nastat po smazání vyhledávacího dotazu respektive při uložení dotazu nového se stejným jménem, jako měl ten smazaný. V takovém případě vyskočí chybová hláška, že toto jméno již existuje – ale ono neexistuje, nebo přesněji uživatel žádný dotaz s takovým jménem mezi Vyhledávacími dotazy nevidí.

![image](https://user-images.githubusercontent.com/57805328/71982290-6ef54280-3224-11ea-92ad-9988c1fce09e.png)

**Comment by yantom** [comment]
Opraveno v aktuální verzi.

**Comment by kerschfilip** [comment]
Z pohledu uživatele _arc-bob_ nebo i například _arc-analyst_ funguje vše jak má, ale zkusím-li kliknout na záložku Vyhledávací dotazy ze svého účtu _kersch_ zobrazí se jen chyba. Čím to může, prosím, být?
![image](https://user-images.githubusercontent.com/57805328/74014070-2d27fb00-498e-11ea-85a3-eb5c7d748cfd.png)

**Comment by yantom** [comment]
Problém byl způsoben tím že jsme se při nasazení snažili zachovat Vaš dříve uložený dotaz, bohužel však odkazoval na entity u kterých se v novém release měnila struktura. Dotaz jsme vymazali problém by tím měl být vyřešen.

**Comment by kerschfilip** [comment]
Aha, díky. Teď už všechno funguje
