### ISSUE TITLE
Stažení AIP XML

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#48]
Z aplikace na https://arclib-test.lib.cas.cz nelze stahovat AIP XML ani celý AIP. Příkaz vrátí pro všechny balíčky identické [xml](http://leteckaposta.cz/201602217). V aplikaci na původní adrese inqooltest-arclib.libj.cas.cz operace stažení vrací v případě AIP XML korektní výsledek. Testováno pod účtem vasek nad AIP s ID 94d6826e-ba19-41bd-8199-81d7c58a12ff na obou instalacích.

**Comment by ZdenekVasek** [comment]
Znovu otestováno, nekorektní chování trvá, ale platí pouze pro Firefox. V Chrome se chová korektně. Berte tedy pouze jako upozornění pro zohlednění při dalším testování. Beru na vědomí, že testovat je třeba v Chrome.

**Comment by yantom** [comment]
Prosím o přetestování. Kolegovi se stále nedaří nasimulovat, ale pokusil se download trochu přepsat "na slepo".

**Comment by ZdenekVasek** [comment]
Test proveden, chování se zdá být korektní. Lze tedy uzavřít.
