### ISSUE TITLE
Problémy s interpunkčními znaky při vyhledávání

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#49]
Ve vyhledávacích polích Dublin core a Document nelze vyhledávat řetězce obsahující některé interpunkční znaky: 

- V případě dvojtečky v poli Dublin core systém rovnou hlásí chybu "400 Error" v poli Document chybu nenahlásí ale nedá žádný výsledek - ověřováno na identifikátoru "urn:nbn:cz:nk-0016ke". 

- Podobně je v obou polích bez chyby ignorován dotaz s pomlčkou, ověřeno na identifikátoru UUID: "6d5a1810-0377-11e4-9806-005056825209".

- V poli Document hlásí chybu "400 Error" také například vyhledání řetezce <mods:identifier type="uuid">6d5a1810-0377-11e4-9806-005056825209</mods:identifier> - zde problém způsobují zřejmě uvozovky v hodnotě atributu. 

Jsou to jen zjištěné příklady, je potřeba ošetřit obecně. Díky.

**Comment by yantom** [comment]
První dva případy byly opraveny v aktuální verzi.

S podporou vyhledávání dle XML fragmentu jsme nepočítali, je toto opravdu potřebné? Umožňujeme vyhledávat pouze v obsahu XML elementů, elementy samotné neindexujeme.

**Comment by vjirousek** [comment]
První dva body vypadají OK. Díky. 

Třetí bod můžeme probrat znovu zítra na schůzce. Potřebné by mi to přislo například v případě, že bych chtěl vyhledat balíček obsahující nějaký identifikátor a chci vyhledat jen balíček, kde je tento identifikátor uveden jako zrušený, nebo spíše jen ten, kde je nezrušený:

<mods:identifier **invalid="yes"** type="ccnb">cnb000390254</mods:identifier>

Vyhledávání jen nad hodnotou pole bez atributů není v daném případě dostačující.

**Comment by yantom** [comment]
Bylo dohodnuto že bude zapracováno i vyhledávání dle XML fragmentu.

**Comment by yantom** [comment]
@vjirousek
Bylo implementováno indexování textu per element - sekce **Obecné hledání v celém XML**. Pro vyhledání výsledku zadáte
* název XML elementu = identifier
* název kteréhokoliv atributu = invalid
* hodnota kteréhokoliv atributu = yes

Nové vyhledávání bude fungovat pouze u nově ingestovaných balíků, jeden takový jsem Vám zde nahrál, pro jeho nalezení vyfiltruje **XML ID = ARCLIB_000003175**.

**Comment by vjirousek** [comment]
Děkuji, diskutované případy užití při vyhledávání nad bibliografickými metadaty v MODS to takto myslím splňuje.
