### ISSUE TITLE
Nefunkční tlačítka Download AIP a Download XML

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#5]
Ve výsledku vyhledávání ani v záznamu AIP balíčků nefungují tlačítka Download AIP a Download XML (po kliknutí se nic neděje). Případně možná špatně chápu jejich účel, v obou případech dle dokumentace očekávám stažení do PC odkud přistupuji. U stažení celého AIP bych nicméne chápal, pokud by docházelo pouze k uložení na předem definované úložiště. Případně tedy prosím o vysvětlení.

**Comment by vjirousek** [comment]
Problém se vyskytuje zřejmě jen ve Firefox, konkrétně zjištěno u Firefox 60.4.0 ESR (64-bit). V Explorer, Edge i Chrome je stahování funkční.

**Comment by hochla-simon** [comment]
Otestované vo Firefox 64.0 (64-bit), preferujeme použitie aktuálnych verzií prehliadačov

**Comment by vjirousek** [comment]
U části balíčků stahování funguje, u jiných dostávám chybu která mi není zcela srozumitelná:
![obrazek](https://user-images.githubusercontent.com/22765973/52916275-83afab80-32dd-11e9-9346-571f140ed4a0.png)

**Comment by yantom** [comment]
bug se týká všech balíků které byly ingestovány s dodavatelským profilem který ma nastaven režim ladění na true

**Comment by vjirousek** [comment]
Zdá se být OK, díky.
