### ISSUE TITLE
Nemožnost zadávat vyhledávací dotazy do webového rozhraní

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#50]
Během práce s vyhledávacím prostředím dochází k situacím, kdy nelze do jednotlivých řádků zadat jakékoliv hodnoty. Při kliknutí do jakéhokoliv pole, kam lze vyplnit hledané hodnoty, prostředí nereaguje. Nelze psát. Při refreshi prohlížeče problém zmizí. Zaregistrováno na Chrome i Firefox. Výskyt je náhodný. Nejméně u 4 uživatelů. Žádná kauzalita nezjištěna.

**Comment by yantom** [comment]
Opraveno v aktuální verzi.

**Comment by ZdenekVasek** [comment]
Po této opravě se chyba nevyskytla. Aktuálně souhlasím s vyřešením.
