### ISSUE TITLE
Selhání Ingestu: exception decoding Hex string

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#51]
Při ingestu došlo k selhání `INTERNAL_ERROR`, zpráva: `exception decoding Hex string: String index out of range: 7`. Jednalo se o _Ingest workflow ARCLIB_000000375_

V čem může být chyba? Obdobné balíky při stejné konfiguraci projdou ingestem bez problému.

Díky za pomoc!

**Comment by yantom** [comment]
Dobrý den, jedná se o bug, děkujeme za nahlášení.

**Comment by yantom** [comment]
Opraveno v aktuální verzi.

**Comment by kerschfilip** [comment]
Ingest stejného SIP již proběhl bez problému, Díky!
