### ISSUE TITLE
V novém release nelze editovat producer profile

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#52]
Aktuálně nelze editovat producer profile, a to ani s přiřazenými rolemi ADMIN a SUPER_ADMIN, které by dle wiki měly editaci producer profilu umožnit.

**Comment by yantom** [comment]
Opraveno.

**Comment by jbil7** [comment]
Funguje. Děkuji!

**Comment by jbil7** [comment]
Issue je možné zavřít. Mně to z neznámého důvodu nejde.
