### ISSUE TITLE
Nelze znovu použít jméno smazaného producer profilu

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#53]
při pokusu o založení nového producer profilu, jehož název se má shodovat s názvem producer profilu, jenž byl v minulosti smazán, dojde k následující chybě:

> 409 Error
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "arclib_producer_profile_name_key"
Detail: Key (name)=(JBil - test profil 2) already exists.

Je toto chování žádoucí? Ve wiki kapitole k producer profilu, hledal-li jsem správně, se nic o nemožnosti založení producer profilu, jehož jméno bylo v minulosti užito, nepíše.

**Comment by yantom** [comment]
Děkujeme, jedná se o stejný problém který se dříve vyskytoval u vyhledávacích dotazů. Problém se vyskytuje u více entit, bude hromadně opraven v následujícím release.

**Comment by yantom** [comment]
Opraveno

**Comment by jbil7** [comment]
Funguje, děkuji!

**Comment by jbil7** [comment]
Funguje, děkuji!

**Comment by jbil7** [comment]
Funguje, děkuji!
