### ISSUE TITLE
Nelze pokračovat ani zrušit pozastavený ingest

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#54]
Dobrý den,

při ingestu některých balíčků se mi stalo, že proces trval moc dlouho a zdálo se, že nic nedělá (v sekci Ingest workflow není ani jedna probíhající nebo proběhlá událost). Ingest těchto balíčků jsem pozastavil a nyní není možné jej znovu spustit nebo úplně zrušit.

Při pokusu o pokračování v ingestu se objeví hlášení:

> Dávka nemohla být obnovena kvůli probíhajícím ingest workflows.

žádná ingest workflows ale v tu chvíli neprobíhala

A při pokusu o zrušení ingestu:
> 500 Error
java.lang.NullPointerException

Jedná se například o Ingest workflow ARCLIB_000000404, 405

Možná to nějak souvisí s tím, že jsem jako Hash typ použil Sha512 místo MD5, ale možná je to taky úplně falešná stopa :)

**Comment by yantom** [comment]
Operace pozastavit/zrušit/pokračovat se vztahují na celou dávku, nikoliv na jednotlivé ingesty. Pozastavení způsobí že se dávka přepne do stavu pozastaveno a ingesty které ještě nezapočaly nezapočnou, ty již běžící však musí skončit, což se neděje, chybu investigujeme.

**Comment by yantom** [comment]
Sha512 by mělo být podporováno ale pravděpodobně byl zaslán zlý otisk. Důvod proč IW zamrzlo a neskončilo hned s chybou je stejný jako důvod proč pokus o zrušení dávky vrací 500 - Null pointer exception. Opravu nasadíme ještě dnes.

**Comment by yantom** [comment]
Opraveno. Dávky již lze zrušit a ingesty s nevalidním hashem korektně končí s chybovou hláškou. Nemožnost spustit pokračování dávky pokud některý ingest stále běží je validní chování.

**Comment by kerschfilip** [comment]
Děkuji za vysvětlení.

Zdá se, že teď vše funguje, jak má, díky!
