### ISSUE TITLE
dotaz: Může SIP obsahovat podsložky s jednotlivými balíčky?

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#55]
Dobrý den, 

rád bych se zeptal, zda umí/bude umět ARCLib ingestovat SIP vícedílné monografie či periodika, tedy takový, kde samotný archivační balíček obsahuje v podstatě několik dalších SIP (v každé podsložce jsou vlastní obrazová data, vlastní mets, atd) - viz obrázek
![image](https://user-images.githubusercontent.com/57805328/74030297-00381000-49af-11ea-9dab-d76013deb07a.png)

Je možné to nějak nastavit, nebo je a bude třeba vždy ingestovat balíky po jednom?

Omlouvám se, bohužel jsem nikde tuto informaci nenašel

Děkuji

**Comment by yantom** [comment]
Dobrý den pro toto v současnosti v systému podpora není. Každý SIP musí mít jeden hlavní metadatový soubor a musí mít přiděleno autorské ID extrahované z některého metadatového souboru.

**Comment by kerschfilip** [comment]
Dobře. Díky za informaci.
