### ISSUE TITLE
Důvod editace

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#56]
Při editaci ARCLib AIp XML lze zapsat důvod editace. Lze tento důvod někde vyhledat? Např. u balíčku s ID 18af2040-b8b7-4eb3-9175-0eeab0c55e4c.

**Comment by ZdenekVasek** [comment]
Důvod se zapisuje do PREMIS, předtím jsem to neviděl. Je to tedy vyřešeno.

**Comment by yantom** [comment]
Situaci jsem prověřoval. Metadata modification event je zapsán pouze u balíků verzí 5.2 a 5.3. Verze 5.4 byla vytvořena ingestem skrze rutinu, její AIP XML tyto eventy neobsahuje (což je předpokládám správně, vzhledem k tomu že balík ingestovaný v rámci rutiny je identický s tím ve verzi 1.1). Možná právě to bylo důvodem přehlédnutí.

**Comment by ZdenekVasek** [comment]
Děkuji za vysvětlení.
