### ISSUE TITLE
Nesedící MD5 ve filesection

### ISSUE THREAD

**Issue by pavlaskovae** [LIBCAS/ARCLib#57]
Dobrý den,

při pokusech s ingestem jsem na zřejmě narazila na problém s generováním MD5. V ukázkovém balíčku pro ingest jsem nahradila 2 jp2 soubory soubory PDF a mp4, aniž bych měnila doprovodná metadata. Droid je korektně identifikoval a do ARCLib XML byl zapsán výsledek kontroly MD5, které samozřejmě neodpovídalo tomu uvedenému v producentských metadatech. Nicméně zdá se, že nové MD5 nebylo vygenerováno, respektive jeho hodnota ve fileSec neodpovídá danému souboru. Přikládám problematické XML [18af2040-b8b7-4eb3-9175-0eeab0c55e4c_xml_4.txt](https://github.com/LIBCAS/ARCLib/files/4192129/18af2040-b8b7-4eb3-9175-0eeab0c55e4c_xml_4.txt)

**Comment by yantom** [comment]
Dobrý den, do filesec jsou skutečně zapsány hodnoty z původního filesec, generovaná MD5 je použita pouze pro kontrolu. Pravděpodobně jsme si nebyli jisti kterou hodnotu zde v tomto případě zapisovat. Opravu nasadíme v příštím release.

**Comment by yantom** [comment]
Dle domluvy je nyní do filesec zapisován vždy SHA512 checksum generovaný ARCLibem.

**Comment by yantom** [comment]
Oprava: v rámci tohoto issue byla pouze nasazena oprava daného checksumu v AIP XML (nyní je zde vkládán checksum generovaný ARCLibem, který odpovída checksumu vloženého souboru) jeho typ však stále závisí na typu checksumu uvedeném v původním METS (pokud byl v původním METS MD5 vygeneruje se MD5). Upnutí na SHA512 bude implementováno až v rámci issue #61

**Comment by pavlaskovae** [comment]
Děkuji za úpravu. Otestovala jsem a Arclib vkládá korektní MD5.
