### ISSUE TITLE
Chyby při ingestu

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#58]
Nedaří se vložit žádný jiný SIP kromě vzorového. Použit vzorový balíček NDK dostupný z odkazu https://owncloud.cesnet.cz/index.php/s/aSpRBXKWQerOVv0/download. Balíček byl přejmenován dle uuid, má zcela stejnou strukturu jako vzorové Hlasy ze Sionu, ale nepodařilo se provést ingest. Výsledkem je tato chyba
![arclib](https://user-images.githubusercontent.com/26565876/74727417-6b9ca000-5241-11ea-94e2-b6c80bbfd467.jpg)
Nevidím ve struktuře balíčku ani v samotném mest žádnou chybu. Prosím o reakci.

**Comment by yantom** [comment]
Jedná se o chybu. Děkujeme za nahlášení.

**Comment by ZdenekVasek** [comment]
Doplnění: podařilo se vložit i další SIP, konkrétně ARCLIB_000000475, nicméně u nahlášeného balíčku chyba trvá a nevidím na první pohled žádnou chybu ve vstupních datech.

**Comment by yantom** [comment]
Jednalo se o chybu při unzipování dodaného balíků v ARCLibu, pořadí unzipovaných souborů bylo závislé na názvu balíku. Chyba byla opravena. [Balík nyní prochází ingestem](https://arclib-test.lib.cas.cz/ingest-batches/53748019-20b9-4206-83b7-abd14290078f)

**Comment by ZdenekVasek** [comment]
Potvrzuji úspěšný průchod a uzavírám.
