### ISSUE TITLE
Rozšíření možností vyhledávání

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#59]
Jako výsledek testování navrhuji upravit rozhraní pro vyhledávání tak, aby nově byla dostupná možnost zaškrnout volbu "zobraz jen poslední verze". Jde o to, že jiném hledání než konkrétního ID se zobrazují všechny verze, což je za některých situací žádoucí, ale jindy by bylo třeb, abych viděl jen aktuální verze, kvůli přehlednosti. Dávám ke zvážení jako požadavek na rozšíření.

**Comment by yantom** [comment]
Implementováno a nasazeno.

**Comment by ZdenekVasek** [comment]
Otestováno. Potvrzuji funkčnost.
