### ISSUE TITLE
Chyba: Editation lock failed!

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#6]
Při snaze o editaci arclib XML systém u řady balíčků hlásí "Editation lock failed!." Chyba není pod tímto komentářem v dokumentaci přímo popsána, předpokládám nicméně že jde o konflikt v editaci s dalším uživatelem. Pokud je tomu tak, bylo by možné chybovou hlášku upravit tak, aby uživatel obdržel informaci kým je daný soubor aktuálně editován a od kdy jej má takto "rezervován"?

![obrazek](https://user-images.githubusercontent.com/22765973/51548816-67008f00-1e69-11e9-806e-e545f2c2de6e.png)

**Comment by vjirousek** [comment]
Ještě koukám že u některých AIP volba EDIT vůbec není, takže možná výše uvedená hláška s konfliktem vůbec nesouvisí. Prosím tedy případně též o vysvětlení kdy editace není k dispozici. Děkuji.

**Comment by hochla-simon** [comment]
Ďakujeme za upozornenie. Pravdepodobne nedošlo kvôli použitému prehliadaču ku správnemu odomknutiu balíka na konci editácie, na odstránení chyby pracujeme. Momentálne už je možné všetky balíky na serveri editovať, zámky som manuálne deaktivoval.

Editácia ArclibXml je vždy k dispozícií iba u najnovšej verzie AIP balíka, t.j. ak napríklad existujú verzie 1.1, 1.2, 1.3, 2.1, 2.2, tak je k dispozícií iba u 2.2

**Comment by hochla-simon** [comment]
Opravené, otestované prípady:
1. pokus o násobnú editáciu daného XML tým istým užívateľom vo viacerých kartách: pri opakovanom pokuse o získanie zámku nad tým istým XML (podľa správnosti) editácia zlyhá
2. pokus o násobnú editáciu daného XML viacerými rôznymi užívateľmi: zámok pre editáciu sa podarí získať iba prvému z užívateľov
