### ISSUE TITLE
Chyba se *.zip z Dropboxu

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#60]
Balíčky stažené jako .zip z DropBox padají v ArcLibu, protože nejdou rozbalit. Nevnímám jako chybu zadání ARCLibu, pouze upozorňuji na toto chování.

**Comment by yantom** [comment]
Chyba byla opravena. Balíčky z Dropbox i z jiných nástrojů tvořící ZIP obdobným způsobem by již měly projít.

**Comment by ZdenekVasek** [comment]
Potvrzuji, že balíček z DropBox byl ARCLibem rozpoznán a otevřen. Lze uzavřít.
