### ISSUE TITLE
Chyba při vyloučení nepovinné procedury "fixity check"

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#61]
Dle dokumentace přísluší "fixity check" mezi volitelné procedury (https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow). Zkusil jsem tedy ve Workflow definitions tento krok vyloučit (pomocí _Camunda_ aplikace) a všechny ingesty s použitou definicí wf skončily v této chybě:

> eq(null) is not allowed. Use isNull() instead; nested exception is java.lang.IllegalArgumentException: eq(null) is not allowed. Use isNull() instead

Zkusil jsem odmazat i fixity check v JSON konfiguraci ingestu / producer profilu, chyba však přetrvává. Ačkoliv se v praxi s vyloučením fixity_checkeru spíše nepočítá, chci se zeptat, jestli byl můj postup správný a zda se nejedná zde spíše o bug (případně rozpor s dokumentací ohledně povinnosti této procedury).

**Comment by yantom** [comment]
Váš postup byl správný, dokonce není nutno odmazávat sekce v configu. Jedná se o chybu / nedořešenou implementaci. Po společné revizi které tasky ponechat jako volitelné a s kterými počítat vždy se na toto zaměříme a upravíme dle dohody.

**Comment by yantom** [comment]
Nasazena oprava a aktualizována wiki: https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow . Proces nyní projde i bez fixity checkeru, viz. vzorový ingest: http://inqooltest-arclib.libj.cas.cz/ingest-workflows/ARCLIB_000001125

**Comment by kerschfilip** [comment]
_Fixity checker_ je nyní možné při ingestu vynechat, stejně jako _validaci_

Ve chvíli, kdy je ale vyloučena procedura _format identifier_ nebo _antivirus_, končí ingest selháním, a to chybou (vznikající asi při validaci AIP XML): 

> MissingNode{xpath=/mets/amdSec/digiprovMD/mdWrap[@MDTYPE='PREMIS']/xmlData/event/eventDetail}

opět se v praxi asi nedá předpokládat, že by byly tyto procedury vynechávány, ale vzhledem k tomu, že jsou i po aktualizaci wiki označeny jako nepovinné, mělo by asi být možné je vyřadit...

**Comment by yantom** [comment]
Popsáno zde: https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow#non-compulsory-tasks , výstup formátové identifikace je nyní povinný, jelikož je v konfiguračním souboru na úrovni celého systému nastaveno že výstup tohoto tasku se má kontrolovat, viz. tabulka: https://docs.google.com/spreadsheets/d/1OR_NyrTfajZo5emu4PV2c0-pA3D6s2E6lcyx2cJXzLU/edit?usp=sharing , sloupec **check existence**, řádky **36-42** 
Platí tedy že tasky zmíněné v sloupci **data source** které mají zároveň nastaveno **check existence = true**, jsou také povinné, zde je ale povinnost konfigurovatelná na úrovni systému. Toto můžeme probrat na schůzi.

**Comment by yantom** [comment]
Do odkazované kapitoly na wiki byl přidán odkaz na online dokument (dříve zde byl odkaz pouze do zdrojových kódů, které jsou narozdíl od WIKI updatovány vždy až s novým release).

Mohl bych poprosit o odkaz na ingest workflow ve kterém neprochází ingest kvůli vynechanému antiviru? Zatímco u formátové identifikaco je to vzhledem k výše popsanému očekávané, u antiviru by k pádu docházet nemělo. Situaci prověříme.

**Comment by kerschfilip** [comment]
> formátové identifikace je nyní povinný...

Aha díky, toho jsem si nevšiml, moje chyba. 

Ingest, který neprochází bez antiviru je např [ARCLIB_000001323](https://arclib-test.lib.cas.cz/ingest-workflows/ARCLIB_000001323), z nastavených nepovinných tasků je zařazena jen  formátová identifikace ( použitá [WF-def.](https://arclib-test.lib.cas.cz/workflow-definitions/76fc3a50-98dc-11ea-8510-6102dce7ec63) )

>  Toto můžeme probrat na schůzi.

Možná by opravdu nebylo špatné to probrat, nevím. Z toho jak to chápu já, by WF definice měly být nastavitelné administrátorem, ten ale nejspíš nebude mít (a asi by ani neměl mít) přístup k editaci konfiguračního souboru na úrovni celého systému...

**Comment by yantom** [comment]
Bude opravena nahlášená chyba. Zároveň bude kontrola existence vybraných elementů přenesena do samostatného BPM tasku - tak aby mohla být ušitá na míru pro jednotlivé workflow definitions.

**Comment by yantom** [comment]
1) Zrevidoval jsem stávající stav. Tabulka https://docs.google.com/spreadsheets/d/1OR_NyrTfajZo5emu4PV2c0-pA3D6s2E6lcyx2cJXzLU/edit#gid=586517350 obsahuje 2 podobné sloupce: _1. Must be present_ a _2. Check existence_. První z nich je sepsaný programátory a příznak TRUE je zde u uzlů které v ARCLib XML musí existovat pro interní chod systému, ať už jsou vytaženy pomocí XSLT nebo generovány systémem, je to vlastně informace spíš pro programátory. Druhý sloupec je nadmnožinou prvního a příznak TRUE zde mají všechny elementy které byly v historické verzi tabulky označeny jako povinné již v roce 2017. Tedy první sloupec říká: bez těchto uzlů v ARCLib XML nebude systém schopný fungovat, druhý říká: tyto uzly bychom chtěli mít v ARCLib XML vždy přítomné.

2) Příkladem je již zmíněná formátová identifikace, bez které se systém jako takový obejde ale pravděpodobně z důvodu metodiky byl její výstup od začátku označen jako povinný. Atribut povinnosti vnímám tedy spíše jako kus zdrojového kódu reflektující metodiku, než jako něco co by mělo být konfigurovatelné per workflow. Myslím tedy že formátová identifikace by měla být v dokumentaci označena za povinnou a mnou navrhované řešení z minula: _"kontrola existence vybraných elementů přenesena do samostatného BPM tasku"_ navrhuji zneplatnit.

3) Co se systémového ověření povinných uzlů týče, velká část (všechny pro které platí "Check existence" = TRUE && "Data source" startstwith "SIP profile XSLT") byla přesunuta do tasku provádějícího XSLT dle SIP profilu (ArclibXml Extractor), viz https://github.com/LIBCAS/ARCLib/issues/73#issuecomment-721365591 
Zbylé elementy jsou kontrolovány v generátoru ARCLib XML. 

4) Chyba na kterou jste narazil je způsobena neúplnou implementací systémového ověření - kontrolu existence uspokojí že najde jakýkoliv detail události (eventDetail) v celém XML, místo toho aby kontrolovala že každý event má svůj detail. U některých eventů detail chybí, přičemž je ale eventDetail již historicky označen za povinný uzel a systém by ho měl generovat. Vidím zde tedy dva body k implementaci 1) přepsat kontrolu aby fungovala očekávaným způsobem, 2) generovat eventDetail ve všech událostech.

**Comment by yantom** [comment]
Dohodnutí z dnešní schůzky:

1) Formátová identifikace bude ve wiki označena za nepovinou, v dokumentaci bude ale uveden odkaz na tabulku s informací že i nepovinné tasky mohou být konfigurací systému vyžádovány.
2) Bude opravena chyba v kontrole zmíněná v bodě 4, dále bude umožněno kontrolu konfigurovat na úrovni profilu - nastavit jeden ze tří stavů: nekontrolovat, kontrolovat s varováním, kontrolovat s chybou.
3) eventDetail bude defaultně nastaven jako nepovinný

**Comment by yantom** [comment]
Upřesnění bodu 4 z [komentáře z 10.11.2020](https://github.com/LIBCAS/ARCLib/issues/61#issuecomment-724720640) : vyřazení antiviru není problém, problém je ve špatné implementaci kontroly dle sloupce  _Check existence_ (bude přeimplementován dle závěrů v komentáři 26.11.2020). Pokud nyní např. vyřadíte antivir ale zároveň necháte zařazené všechny ostatní tasky, ingest bude fungovat. Přiložená definice z komentáře 18.5.2020 vyloučila více nepovinných tasků zároveň, což způsobí problém v _Check existence_ funkcionalitě.

**Comment by yantom** [comment]
Vše upraveno dle dohody ze schůzek zaznamenané v posledních komentářích. Úprava nasazena na TEST server a zdokumentována, Doc update:

The Ingest - Archival Process
- Format Identifier moved to non compulsory tasks with a note about methodological recommendation and system-wide validation
- ARCLibXML extractor and ARCLibXML generator validation description update + json config options to skip system-wide validation introduced

odkaz z dokumentace na arclibXmlSystemWideValidationConfig.csv bude funkční po nahrání poslední verze zdrojových kódu

**Comment by kerschfilip** [comment]
@jbil7 můžeme issue zavřít? Za mne je to teď OK. Děkuju!

**Comment by jbil7** [comment]
Ano, můžeme uzavřít.
