### ISSUE TITLE
Chybějící zpráva o použitých profilech (procesních proměnných) u dávky končící v chybě během preprocessingu

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#62]
Dojde-li k chybě hned na počátku ingestu, jako např. v případě `Ingest workflow ARCLIB_000000492`, procesní proměnné, v normálním případě informující o užitých profilech, jsou prázdné.

Je v tomto případě nějaká možnost, jak zjistit, které profily byly užity při ingestu? Děkuji!

**Comment by yantom** [comment]
Toto určitě zahrneme již v tabu detailu IW (procesní proměnné pak obsahují proměnné uložené v rámci procesu v Camunda BPM, zde zůstane sekce prázdná jelikož proces nezapočal).

**Comment by yantom** [comment]
Zároveň bude implementováno zobrazení cesty k souboru v transfer area.

**Comment by yantom** [comment]
Implementováno. Procesní proměnné jsou u nových ingestů zobrazeny na detailu IW. Cesta v překladišti je zobrazena i u stávajících.

**Comment by jbil7** [comment]
Ověřeno na základě chybně vložené hodnoty hash při ingestu. Zdá se být funkční, děkuji!
