### ISSUE TITLE
Ve staženém AIP vzniklém v debugging mode chybí přípony

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#64]
Proběhne-li ingest v debugging mode, pak stažený zip AIP balíku obsahuje soubory, kterým chybí přípona. Správně by se mělo jednat o .xml a .zip. Pokud proběhne ingest v ostrém chodu, přípony souborů v zipu jsou v pořádku.

**Comment by yantom** [comment]
Opraveno, možno ověřit na libovolném balíku ingestovaném v debug módu.

**Comment by jbil7** [comment]
Ověřeno. Děkuji!
