### ISSUE TITLE
Chybí možnost aktualizace formátového profilu

### ISSUE THREAD

**Issue by ZdenekVasek** [LIBCAS/ARCLib#66]
V předchozích verzích ARCLIb byla k dispzici (pomocí tlačítka v GUI) možnost aktualizovat definici formátového profilu ve formátové knihovně. Šlo o možnost aktualizace z lokálního profilu nebo z PRONOM. Nyní již tato funkce dostupná není. Jaký k tomu byl důvod a bude nahrazena jinak? (pravidelné dotazy do PRONOM, možnosti pro technického správce atd.). Děkuji.

**Comment by yantom** [comment]
Tlačítka se nacházi na detailu formátu např. zde: http://inqooltest-arclib.libj.cas.cz/formats/147

**Comment by ZdenekVasek** [comment]
Dobrý den, děkuji za reakci. Bohužel tam ovladač nevidím. Viz obrazovka. Vyzkoušena v Chrome a ve Firefox. Prosím o další upřesnění, asi něco přehlížím. Děkuji.
![Screenshot_2020-03-02 ARCLib](https://user-images.githubusercontent.com/26565876/75670293-bfb17680-5c7c-11ea-836b-9d30ebb13a5e.png)

**Comment by yantom** [comment]
Přidal jsem Vám roli SUPERADMIN, zkuste prosím nyní. Informaci o nutnosti autorizace jako SUPERADMIN přidáme do dokumentace zde: https://github.com/LIBCAS/ARCLib/wiki/Usage@Preservation-planning

Pokud byste chtěl roli odebrat můžete tak provést přes arc-bob nebo napište zde a roli odeberu.

**Comment by ZdenekVasek** [comment]
Děkuji, funguje. Stačilo mne odkázat na arc-boba. Ale je logické, že aktualizaci formátového profilu by měli dělat i pracovníci, co nejsou v pozici Superadmin.

**Comment by yantom** [comment]
Pokud to má být umožněno i jiným rolím prosím zadejte nám kterým a my toto
upravíme.

**Comment by yantom** [comment]
Stojí za zmínku že SUPERADMIN i formátová knihovna jsou globální - nejsou
vázáni na konkrétního dodavatele. Ostatní účty jsou naopak vázány k právě
jednomu dodavateli. Je tedy otázkou zda umožnit editovat globální entity
uživatelem který má v systému lokální oprávnění.

**Comment by ZdenekVasek** [comment]
Děkuji, to je podstatná poznámka. Proberu s kolegy a vyjádříme se.
