### ISSUE TITLE
Problémy s Ingest routines

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#67]
Dobrý den,

Při testování mám určité problémy s používáním Ingest routines.

**Nedaří se mi Ingest Routine spustit**
nejsem si jistý proč, jsem přesvědčený, že s obdobným nastavením dřív vše fungovalo správně. Mohl bych poprosit o pomoc? Jedná se například o Ingest routines/ FK_IR (35f97e90-5ee0-11ea-b257-d963c2e3c3c6)
Je přiřazen profil dodavatele, který při manuálním ingestu normálně funguje. Je nastavena cesta do překladište, kde podle FTP jsou balíky i .sums k ingestu a je nastaven CRON (0 20 14 * * ?), který by podle mě měl být validní. Nerozumím tedy tomu, proč ingest batch nezapočne, jestli se jedná o chybu nebo dělám něco špatně já. Díky

**Nelze smazat konkrétní Ingest routine**
jde o FK_IR (9b08a640-3900-11ea-b083-97f660b97870)
Při pokusu o smazání vznikne chyba:

> 403 Error
> cz.cas.lib.arclib.exception.ForbiddenException: Can't delete routine when there is unfinished batch: 793f2bd0-5907-4e71-ab7a-4eadc51daacd which was created by this routine.  

Možná že je chyba spojena s #54 , ostatní IR mazat normálně jde

**Comment by yantom** [comment]
Toto chování by bylo korektní za předpokladu že by zmíněná dávka 793f2bd0-5907-4e71-ab7a-4eadc51daacd nebyla v koncovém stavu - v tom případě nelze smazat rutinu na základě které byla dávka vytvořena a ani nezapočne nová dávka dokuď původní nedoběhne.

Dávka však v koncovém stavu je, tedy systém se dostal do nepředpokládaného stavu - toto musíme prošetřit. Prozatím jsem provedl opravu v DB tak aby Vám dávky běžely. V případě že se situace zopakuje, prosím o notifikaci a operativně opět upravím.

**Comment by yantom** [comment]
Chybu se nepodařilo zreprodukovat. Pravděpodobně vznikla jako důsledek jiné chyby nebo byla v rámci uplynulého časového období nezáměrně opravena. Vzhledem k ojedinělosti navrhuji uzavřít.

**Comment by kerschfilip** [comment]
Se zmíněnou chybou jsem se již nesetkal, souhlasím s uzavřením.
