### ISSUE TITLE
Odhlášení uživatele při delší nečinnosti

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#69]
Arclib neodhlásí uživatele i po dvoudenní nečinnosti, dle mého názoru by jej měl automaticky odhlásit po několikahodinové, příp. i několikaminutové nečinnosti--záleží jak bývá u aplikací zvykem.

**Comment by yantom** [comment]
Toto lze nastavit v konfiguračním souboru viz. https://github.com/LIBCAS/ARCLib/wiki/System-Setup#security pro pohodlnost testování je na serveru momentálně nastaveno 900000s = 10 dní.
