### ISSUE TITLE
Chyba: Ingest lze provést pouze s názvovou konvencí užitou v "test SIP package"

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#7]
Při ingestu jiného SIP balíku než vzorového z dokumentace "Instructions for sample ingest" dojde k následující chybě:

> File with metadata for ingest workflow with external id ARCLIB_000000007 does not exist at path: workspace/ARCLIB_000000007/f37f7870-def5-11e6-8a71-005056827e52/mets_7033d800-0935-11e4-beed-5ef3fc9ae867.xml

Ingest nebere v potaz reálný název importovaný souborů a očekává název souborů ze vzorového SIP balíku. V případě výše uvedené citace se importovaný metadatový soubor jmenuje reálně mets_f37f7870-def5-11e6-8a71-005056827e52.xml . UUID 7033d800-0935-11e4-beed-5ef3fc9ae867 pochází ze vzorového balíku, s tímto ingestem nemá mít nic společného.

Po přizpůsobení názvové konvence v celém balíku očekávaným hodnotám proběhl ingest v pořádku.

**Comment by hochla-simon** [comment]
Navrhujeme použiť v SIP profile miesto konkrétnej cesty k súborom **Path to XML file with authorial ID** a **Path to main metadata file of SIP (e.g. METS.xml)** REGEX výraz. Mets súbory spravidla obsahujú v názve slovo **mets** doplnený o sufix. Alternatívou je definovať tieto cesty v .sums súbore (spolu s hashom balíku) u každého ingestovaného balíku zvlášť.

**Comment by jbil7** [comment]
Děkuji Vám za doporučení. Po vyzkoušení jsem ovšem zjistil, že regulární výrazy v těchto polích jsou interpretovány jako běžné znaky. V důsledku toho ingest skončil v této chybě:

> File with metadata for ingest workflow with external id ARCLIB_000000035 does not exist at path: workspace/ARCLIB_000000035/f37f7870-def5-11e6-8a71-005056827e52/mets_*.xml

V obou polích byla vyplněna hodnota `mets_*.xml`, která funguje při vyhledávání ve windowsech i v linuxových systémech. Byly vyzkoušeny i uvozovky, stejně tak `mets_.*.xml`. Prosím, jaký tvar regexu je v tomto případě správný? Děkuji.

**Comment by hochla-simon** [comment]
Momentálne ešte nemáme nasadenú aktuálnu verziu, ktorá používa regulárne výrazy, prevedieme tak v priebehu dnešného dňa.

**Comment by hochla-simon** [comment]
Pre definíciu **Path to XML file with authorial ID** a **Path to main metadata file of SIP (e.g. METS.xml)** možno použiť regulárny výraz vo formáte Java Regex (pozor, nejedná sa o klasický regulárny výraz, je nutné napísať výraz ako typ **exact match** miesto typu **contains**). Dokumentácia formátu: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html, online tester: https://www.freeformatter.com/java-regex-tester.html.

**Comment by jbil7** [comment]
Problém s názvem souboru se nyní přesunul do **Validation profiles**. Prosím, bylo by možné přidat do xsl pro validační šablonu element `<regex>` i pod element `<filePath>`, případně parsovat regexy rovnou v hodnotě elementu `<filePath>`?

**Comment by jbil7** [comment]
Regexy v `<filePathGlobPattern>` již fungují, bohužel však jen v případě, že je tento element dceřiný elementu `<nodeCheck>`. Pokud je element na adrese `/profile/rule/fileExistenceCheck/filePathGlobPattern` (tedy za účelem kontroly přítomnosti souboru, nikoliv nodu uvnitř xml), regexy v hodnotách `<filePathGlobPattern>` nadále nefungují.

**Comment by hochla-simon** [comment]
Pozor, regulárne výrazy boli po novom nahradené výrazmi typu glob: https://en.wikipedia.org/wiki/Glob_(programming), vo vašom prípade sa jedná o regulárny výraz: `.*alto/alto_.*.xml`.

Kontrola typu `nodeCheck` pravdepodobne prešla s regulárnym výrazom iba z dôvodu, že `nodeCheck` fungujú spôsobom, že keď sa nenájde nijaký súbor hodiaci sa na daný glob pattern, tak sa uvedená kontrola nevykoná vôbec (v opačnom prípade sa vykoná na všetkých súboroch, ktoré príslušia danému glob patternu).

Kontrolu prítomnosti súboru sme otestovali použitím výrazu `<filePathGlobPattern>mets_*.xml</filePathGlobPattern>` a všetko prešlo v poriadku.
