### ISSUE TITLE
Část Arclib XML je vizuálně horší ke čtení

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#70]
Nová verze Arclibu vytváří ARCLIB XML ve kterém jsou administrativní/technická metadata zapsána do jednoho řádku nikoliv do stromové struktury jako dříve. Pro strojové zpracování to nevadí, ale pro uživatele je tato část hůř přehledná. Nejedná se o závažnou funkční vadu.
[fc988cda-8dd1-427e-921e-abf166f1701c_xml_1.zip](https://github.com/LIBCAS/ARCLib/files/4306944/fc988cda-8dd1-427e-921e-abf166f1701c_xml_1.zip)

**Comment by yantom** [comment]
Nasazena oprava, vzorový balíček zde: http://inqooltest-arclib.libj.cas.cz/aip/ARCLIB_000001125

**Comment by godnat** [comment]
Otestováno a funguje, díky.
