### ISSUE TITLE
Import stejného balíčku by měl vést k ohlášení duplicity

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#71]
V případě, že je do Arclibu vložen stejný balíček znovu (stejná MD5), Arclib verzuje (verzuje xml). Tato akce by ale, dle mého názoru, měla vést k ohlášení duplicity.

**Comment by yantom** [comment]
Stávající chování je implementováno dle schváleného návrhu.

**Comment by yantom** [comment]
Na základě dohody bude navrhnuto upozornění vkládajícího v případě duplicitních dat a možnost rozhodnout zda je metadatový update vyžadovaný nebo se jedná o omyl.

**Comment by ZdenekVasek** [comment]
Bylo už implementováno?

**Comment by yantom** [comment]
Implementováno a nasazeno, viz testovací dávka https://arclib-test.lib.cas.cz/ingest-batches/0dbef172-0927-4bdb-8d58-ca5ac8ceba01 . Pro vyřešení incidentu je nutné do konfigurace přidat _"continueOnDuplicateSip":true_ Bude zdokumentováno.

**Comment by yantom** [comment]
Zdokumentováno: https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow#duplicate-sip-check-1

**Comment by godnat** [comment]
Otestováno, funguje uvedeným způsobem.

Jen shrnutí pro případ, že by ještě někdo chtěl funkcionalitu ověřit:
Aby systém rozeznal duplicitní balíček, musí být kontrola duplicity přítomná v profilu dodavatele v jeho definici workflow. 
Rozezná se duplicita v případě, že je balíček vkládán pod stejným Profilem dodavatele. Duplicita je incident, který se vyřeší úpravou workflow, přidáním příkazu,  balíček pak doběhne v pořádku a verzuje se.
