### ISSUE TITLE
Jak funguje exportování výsledků vyhledávání

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#72]
Dobrý den, chtěl bych se zeptat jak přesně funguje exportování výsledků vyhledávání - konkrétně tlačítko `Exportovat výsledky vyhledávání ` ve _Vyhledávacích dotazech_. Po nastavení exportní rutiny se totiž nejspíš nic neděje, nebo nevím, kam se export ukládá, protože ARCLib neukazuje cestu do exportní lokace

Zkoušel jsem to i s účtem arc-bob, takže se snad nejedná o chybu spojenou s #47 :-) Díky!

**Comment by yantom** [comment]
Export je proveden v definovaný čas do složky ve workspace na serveru. Cesta by měla být viditelná v GUI, jedná se tedy o chybu.

**Comment by yantom** [comment]
Opraveno.

**Comment by kerschfilip** [comment]
Nedaří se mi potvrdit exportování výsledků vyhledávání. Po kliknutí na _Potvrdit_ se objeví chyba
![image](https://user-images.githubusercontent.com/57805328/80394238-defe0600-88b1-11ea-9ec3-dcd879bd2fe2.png)

**Comment by yantom** [comment]
Opraveno.

**Comment by kerschfilip** [comment]
Bohužel se mi stále zdá, že export spíš nefunguje, než funguje. Při exportu pouze AIP XML se objeví cesta do workspace, ale uvedená složka vůbec nevznikne. Při exportu celých AIP potom složka sice vznikla, ale místo všech AIP ve vyhledávacím dotazu se exportoval pouze jeden balíček

**Comment by yantom** [comment]
Export probíhá přímo z Archival Storage, proto nejsou exportovány balíčky ingestované v debug režimu. Přidali jsme tuto informaci do dokumentace: https://github.com/LIBCAS/ARCLib/wiki/Usage@Search-queries

**Comment by kerschfilip** [comment]
Aha, to mě nějak nenapadlo. Otestoval jsem znovu a funguje :) Takže issue zavírám. Díky!
