### ISSUE TITLE
Uživatelské role

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#74]
Rád bych otevřel diskuzi okolo uživatelských rolí v ARCLibu, abychom zjistili, zda to, jak jsou nyní nastavené, odpovídá tomu, jak chceme systém používat. Otevřít toto téma ostatně už v jednom z mailů navrhl @ZdenekVasek, za což děkuju!

Při testování systému s různými rolemi jsem narazil na pár věcí, které mi připadaly lehce nelogické, například:
- ROLE_ARCHIVIST vidí ingest rutiny, může zakládat nové, ale ne je už editovat nebo mazat 
- ROLE_ARCHIVIST nemůže ukládat vyhledávací dotazy a exportovat na jejich základě 
- ROLE_ADMIN nemá možnost spouštět ingest jednoho SIPu ze záložky Ingest (vůbec ji nevidí) 
- ROLE_ADMIN nemůže zakládat nové ingest rutiny ale může upravovat a mazat stávající 
- ROLE DELETION_ACKNOWLEDGE může stahovat AIP a XML

Rozumím tomu, že záměr byl nejspíš, že jeden uživatel může mít více rolí, přesto nevím, zda by nebylo lepší jednotlivé pravomoce ještě přehodnotit a případně postavit uživatelské role do nějaké jasnější hierarchické struktury, například takto:

![image](https://user-images.githubusercontent.com/57805328/77887644-3d13db00-726b-11ea-86b5-34eef0bff0c3.png)

Jedná se skutečně jen o návrh, budu rád za další názory! Díky!

**Comment by ZdenekVasek** [comment]
Díky, že jste se do toho pustil. Role je potřeba definvat zejména z pohledu budoucích uživatelů. Vzhledem k charakteru ARCLib bych byl pro co nejjednodušší strukturu. Váš návrh mi přijde logický, jen se v jeho rámci zeptám, jak řešíte otázku více dodavatelů? Zda předpkládáte, že nejvýše oprávněný pracovník konkrétního dodavatele bude mít roli administrátor? Jinak máte samozřejmě pravdu, původní úvaha byla více rolí k jedné osobě. Ztratilo se oprávnění spouštět ingest dávky SIPů, jestli jsem v návrhu něco nepřehlédl. A speciální roli editor bych asi spojil se základní úrovní, kterou bych možná přejmenoval na kurátor. Ale to jsou už jen body k debatě.

**Comment by kerschfilip** [comment]
V tomto návrhu předpokládám, že nejvýše oprávněný pracovník konkrétního dodavatele bude mít skutečně "jen" roli administrátora. Superadministrátor by tak byl jeden - z instituce, která zajišťuje infrastrukturu. Je to ale samozřejmě k větší diskuzi...

Oprávnění spouštět ingest dávky SIPů jsem, myslím, shrnul v roli archiváře pod asi ne zcela dobře srozumitelné "nastavuje a spouští IR" :-)

**Comment by kerschfilip** [comment]
Vytvořili jsme v KNAV návrh, který pracuje s menším počtem rolí postavených do jasné hierarchie. Přehled práv těchto rolí je v následující tabulce, jednotlivá práva (akce, které může uživatel s danou rolí vyvolat) jsou v návrhu svázány s položkami menu frontendu. Tabulka je zde: https://docs.google.com/spreadsheets/d/1DMWtxMIV45mqJREAwssVoT0R6070HntB62XRCUcmE3s/edit?usp=sharing

Prosím všechny, kteří mají možnost, zda by se na tabulku podívali a případně ji připomínkovali. Především bych chtěl poprosit InQool, zda by bylo možné se na návrh podívat a rozhodnout, jestli je takto realizovatelný a nechybí v něm nějaké akce - například proto, že nejsou přímo navázány na menu.

Díky!

**Comment by yantom** [comment]
Děkuji, nejprve shrnu 2 rozdíly v návrzích a přidám vlastní komentář. 

| id | @kerschfilip  | @ZdenekVasek | @yantom  |
| - | - | - | - |
| 1 | 1 uživatel - 1 role  | 1 uživatel - n rolí  | Systém je momentálně připraven na 1-n, nicméně 1-1 přijde i mě přehlednější. V kódu můžeme na nižších úrovních zachovat možnost 1-n (a nezavřít si tak dveře do budoucna) ale prezentační vrstvu upravit aby fungovala v režimu 1-1 |
| 2 | role editor neexistuje, nejnižší role je *potvrzování smazání*, editovat XML může pouze *administrátor* a *superadministrátor*  | roli *editor* spojit do základní úrovně | Zde je nesoulad velký, v jednom návrhu může AIP XML editovat "kdokoliv", v druhém pouze admin. **ZV**: Něco jako základní úroveň v současnosti neexistuje, uživatel po prvním přihlášení musí vždy počkat na přiřazení práv administrátorem. Chcete tedy zavést nějakou základní úroveň funkcionalit dostupných bez správy účtu administrátorem? Nebo byla základní úrovní myšlena spíše "nejnižší možná úroveň přidělená administrátorem".  **FK**: Proč je role "potvrzování smazání" v návrhu označena za "speciální roli"? | 

@kerschfilip Váš návrh mi přijde logický. Problémy přicházejí s vazbou na dodavatele.

Součásti Profilu Dodavatele - a) SIP profil, b) Validační profil a c) Workflow Definition - nemají vazbu na dodavatele, tu má až Profil Dodavatele jako celek. Tedy v současnosti nelze "vidět a/b/c svého dodavatele". Pokud si dobře pamatuji, původně se počítalo s tím že administrátoři jednotlivých dodavatelů nebudou tak sběhlí nebo důvěryhodní aby mohli tyto profily tvořit a že je bude nakonec na vyžádání tvořit vždy superadmin. Nicméně pokud je potřeba, s tímto se dá předpokládám hnout aniž by to nějak zásadně zasahovalo do chodu systému.

Reportovací modul není připřaven na reporty specifické pro jednotlivé dodavatele. Nejzásadnější problém je že reportovací šablony jsou naprosto svobodné a je přes ně možné vytáhnout z DB/indexu prakticky cokoliv - zde se opravdu počítalo s tím že reporty budou spravovány systémem/superadminen. Druhý problém je že většina entit nižších vrstev vazbu na dodavatele nemá (má ji až např. nadřazená entita). Report by tedy musel provádět SQL JOIN (i tak je otazné zda by se dal potřebný report sestavit) a tu už se opět dostáváme k tomu že reporty by musel přinejmenším tvořit superadmin.

Tedy úprava oprávnění k Profilům Dodavatelů je rozhodně jednodušší k vyřešení než úprava k Reportům.

**Comment by ZdenekVasek** [comment]
K vlastnímu shrnutí: jak bylo řečeno výše, návrh by měl odpovídat zejména potřebám KNAV, takže bych se plně přizpůsobil návrhům FK. A nemyslím, že jsme v přílišném rozporu v aktuálním nazírání. K bodu 1) rolím - návrh na 1-n byl veden tím, že reálně nebude ARCLib spravovat velký tým lidí, de facto by mělo jít o několik málo jedinců. Původní definice rolí na počátku projektu byla velmi široká, postupně se zužovaly. Idea na počátku spíše byla ve stylu uživatel s určitou množinou práv, která by se skládala z širokého výčtu. Tedy záměr byl, že dva analytici by nutně nemuseli mít stejný rozsah práv. Poté, co se přešlo k identickým rolím, tak důležitá byla i bezpečnost, aby uživatel s více rolemi dělal vždy pod tou, která je adekvátní dané operaci. Ale to je v současném návrhu dost potlačeno a vztah 1-1 je adekvátní. I když se přimlouvám za to, aby alespoň někde na pozadí zůstala možnost 1-n role.
ad bod 2) Tady možná došlo k částečnému nepochopení. V prvním návrhu FK zjednodušil návrh rolí, respektive práv, která byla navržena. Práva, která nezapadala do žádného profilu prezentoval jako "speciální" role. Vzhledem k charakteru systému jsou tyto speciální role asi zbytečné. Ostatní role chápu jako de facto hiearchicky vzestupné, jak vyplývá i z nové tabulky. Navrhoval jsem proto speciální role sloučit s klasickými a vzhledem k charakteru by asi nejlépe vyhovovala role archivář. Vím, že v systému nyní žádná "základní role" není, ale považoval za účelné, aby to tak bylo. Tedy každý nově vytvořený účet by měl oprávnění v rozsahu "archivist" a administrátor by ji mohl "povýšit". Druhou možností je, že by administrátor rovnou přiděloval role a s nimi i množinu práv. To by bylo jednodušší a pak žádná zákaldní role potřeba není. Uživatel bez role i stejně nemohl fungovat. V tomto případě záleží na implementaci. Ale na položenou otázku je správnou odpovědí druhá možnost, tedy nejnižší role přidělitelná administrátorem.

Pokud jde o zbytek diskuse, zde doopravdy záleží na předpokládaném workflow uživatele. Zda se předpokládá zela nezávislé fungování dodavatelů a nebo jen správa jejich dat. Tuhle otázku bych řešil raději na meetingu.

**Comment by kerschfilip** [comment]
Děkuji za shrnutí a komentáře

**1 uživatel - 1 role**\
Pro používání v KNAV by skutečně bylo nejjednodušší nastavit role do režimu 1-1, jsem rád, že i vám se to zdá jako adekvátní a přehledné. Myslím, že návrh upravit prezentační vrstvu na režim 1-1, ale ponechat 1-n nějak na pozadí je ideální řešení

**speciální role potvrzování smazání**\
Zde se jedná jen název role, nic víc za tím není. Počítáme s tím, že ke smazání AIP bude potřeba x potvrzení (jako v současnosti při testování), a protože systém bude používat jen poměrně malé množství lidí (2-3), budou existovat ještě nějakcí další uživatelé, jejichž jediným úkolem bude posouzení a případné potvrzení smazání, proto jsem tuto roli takto nazval. 

**Součásti profilu dodavatele - SIP, validace, workflowdef.**\
Toto je tedy k dalšímu řešení. Z naší interní diskuze vyplynulo, že administrování systému si představujeme tak, že bude existovat superadministrátor, který ale bude se systémem interagovat minimálně. Veškeré nastavování profilů atd by měl mít na starost uživatel s rolí administrátora. Dále by mi přišlo dobré, aby uživatelé vkládající data na denní bázi a řešící problémy při ingestu (archivář a analytik) mohli "vidět" podle čeho balíčky ingestují (například vidět validační profil i z pozice archiváře by mi přišlo užitečné).

**Reportovací modul**\
Zde musím říct, že jsem přesně nevěděl, jak reportování funguje. Má myšlenka za návrhem byla, že si jednotlivý dodavatelé budou moci udělat přehled svých dat v systému. Chápu, že systém byl připraven jinak a myslím, že tedy není problém ponechat reportovací modul pouze superadministrátorovi.

**Comment by kerschfilip** [comment]
Jen doplňuji závěr z diskuze na minulé schůzce, tak jak je v zápisu:

> Pozor, nový návrh je v té tabulce[ Změna uživatelských rolí v ARCLib](https://docs.google.com/spreadsheets/d/1yGVWKpv9JPBHZoOAjoDWZ0AighPLGExVAd7QmWsHFeU/edit#gid=1441115808).
>  - Pozor, v tabulce jsou dva listy.
>
> Nový návrh je přijímán pozitivně, ale ze strany InQool bude vyžadovat netriviální programátorský zásah do návrhu databáze apod.
> 
> Nicméně je třeba vždy u každého uživatele evidovat jeho roli – např. pro znalost, jak nastavit výchozí hodnotu práva, když se systém rozvíjí a nějaké nové právo přibude.
> 
> - Tj. systém rolí, ale s možností nastavování výjimek per právo.
> - Vhodné asi řešit tak, že je možné:
>   - definovat poměrně volně vlastní role, jako kolekce oprávnění,
>   - jeden uživatel má může mít přiřazeno více rolí.
>     - S tím, že jedna je označena jako hlavní.
>   - Výsledná práva jsou sjednocením povolujících práv ze všech přiřazených rolí.
>     - Tj. není tu koncept zakazujícího práva, je možné práva jen přidávat navíc, ne zakazovat z přidělené role.
> 
> Administrátoři nižších úrovní nejsou vázáni na konkrétního dodavatele, chceme některým uživatelům umožnit nastavovat více dodavatelů najednou.
>   - Ať pro to nemusíme zakládat separátní role.
> 
> Reporty nyní běží nad celým archivem.
>   - Mohlo by mít smysl mít reporty běžící např. jen nad daty jednoho dodavatele, ale systém na to nyní není nachystaný, není to možné udělat.
>

**Comment by yantom** [comment]
Implementováno a nasazeno. Pro upřesnění přikládám výňatek ze zápisu 7.7. který lehce přepisuje výstup z 2.7.

```
Pro každého dodavatele bude vytvořen účet lokálního administrátora.
Ten bude mít vazbu na právě tohoto jednoho dodavatele.
Do budoucna by mohlo být užitečné umožnit vazbu účtu na více dodavatelů.
Bude vyžadovat zásahy do kódu aplikace.
Uživatel bude mít přiřazeno n rolí, ale žádná z nich nebude označena jako hlavní.
```

**Comment by yantom** [comment]
Zaevidovali jsme pár nových chyb, oprava by měla být nasazena zítra.

**Comment by yantom** [comment]
Oprava nasazena, je možné testovat.

**Comment by kerschfilip** [comment]
Nové role a oprávnění jsem se pokusil co nejlépe otestovat, celkově mi to připadá dobré, narazil jsem jen na pár nedostatků:

1) V **Profilech dodavatelů** jsou oprávnění nastavena správně a fungují, ale jako položku v menu je vidí pouze superadmin, nikdo jiný ne. 

2) ve **Vyhledávacích dotazech** nefunguje možnost _nové vyhledávání založené na dotazu_ – vždy se otevře jen _vyhledávání AIP_ bez aplikovaných filtrů (platí pro všechny role kromě superadmina)

3) stejně tak nefunguje možnost _Smazat vyhledávací dotaz_ nikomu jinému než superadminovi. Administrátorovi a dalším je vrácena chyba, například: 

> 500 Error org.hibernate.LazyInitializationException: could not initialize proxy [cz.cas.lib.arclib.domain.User#c4be76c0-2993-11eb-acf7-573d9688eea8] - no Session

4) Analytik nevidí ve **Vyhledávání AIP** logicky odstraněné AIP – obnovit ho ale může, když se k němu nějak dostane. Ve vyhledávání vidí pouze AIP ve stavu `ARCHIVED`

5) v **detailu vyhledávání AIP** není (u žádné role) tlačítko `Test on Storage`

6) uživatelé s rolemi admin, analyst a archivist by měli mít možnost pracovat s ARCLibem jen v rámci svého dodavatele, přesto ale v současnosti v **Ingest rutinách**, **Validačních profilech**, **SIP profilech** a **Definici workflow** vidí a podle role mohou i editovat profily příslušící ostatním dodavatelům. Vidět je asi není problém, ale nevím, jak moc je vhodné, aby mohl archivář jednoho dodavatele měnit definici workflow nějakého jiného. Je možné to omezit?

7) Uživatelé s rolemi admin, analyst a archivist vidí v menu položku **Archivační úložiště**, na kterou není možné kliknout. Není to velký problém, ale vzhledem k tomu, že ji k ničemu nepotřebují, bylo by možné ji odstranit? 

8) u rolí superadmin a admin se vyskytuje oprávnění AUTHORIAL_PACKAGE_DELETE, v dokumentaci jsem ho nenašel, k čemu se, prosím, váže?

Děkuji!

(ještě doplnění, oprávnění `EXPORT_ROUTINE_READ` a `EXPORT_ROUTINE_WRITE` nebyly v současné verzi ARCLibu přiděleny rolím analyst a archivist, podle dokumentace to tak ale má být, tak jsem je doplnil)

**Comment by yantom** [comment]
Děkuji za zpětnou vazbu! Na některé z bodů jsme již přišli a pracuje se na nich. Ostatní se pokusíme zapracovat do příštího meetingu. 
K bodu 8: jednalo se o redundantní oprávnění, bude odstraněno
K bodu 6: U těchto entit nemáme vazbu na dodavatele, jak jsem zmíníl v komentáři z 10.6. Nicméně plánujeme ji implementovat, ideálně také do příštího meetingu.

**Comment by yantom** [comment]
Vše opraveno a nasazeno.

**Comment by kerschfilip** [comment]
Děkuji, opravy jsem otestoval a všiml jsi už jen pár problémů:

- uživatel s rolí analytik může obnovit logicky smazaný AIP, ale nemá jak se k němu dostat, protože ve formuláři pro vyhledávání AIP vidí pouze AIP ve stavu `ARCHIVED`
- u rolí analytik a archivář mi stále nefunguje nové vyhledávání založené na vyhledávácím dotazu - teď již jsou filtry z vyhledávacího dotazu propsány do formuláře ve vyhledávání AIP, ale zároveň je vybrán stav AIP `REMOVED` (i když v původním vyhledávacím dotazu bylo vybráno `Vše`), výsledek tak je, že se nezobrazí žádné výsledky.
- u rolí analytik a archivář nefunguje tlačítko `TEST ON STORAGE` - po kliknutí se nezobrazí nabídka úložišť, viz obrázek
![image](https://user-images.githubusercontent.com/57805328/101026277-01a67a80-3577-11eb-8b2d-b7d70e366d09.png)

Vše ostatní se zdá v pořádku, ještě jednou děkuji za rychlou opravu!

**Comment by yantom** [comment]
Nasazena oprava nahlášených chyb. Ještě jsem si všiml Administrátor má v sekcích _Archival storage administration_ a _Roles_ víc oprávnění než by měl. Zadáno do vývoje. Dále byla aktualizována wiki i tabulka, která je nyní z wiki odkazovaná https://docs.google.com/spreadsheets/d/16FW0v0bFdKAKw-tj6iYrAA56Zer325RHrecuvh1lnWI/edit?usp=sharing , nechal jsem zde alespoň druhý tab v češtině, tak jak byl zadán.

**Comment by yantom** [comment]
Nasazena oprava, v tuto chvíli neevidujeme žádné další chyby.

**Comment by kerschfilip** [comment]
Otestováno, děkuji

Všiml jsem si ještě drobnosti: uživatel s právy pouze pro potvrzování smazání vidí u AIP zpracovaného v debug mode tlačítko `Zapomenout`, nemá ovšem (správně) právo tuto funkci používat a po stisknutí se vrací chyba. Tlačítko by tam tak asi v tomto případě nemuselo vůbec být

**Comment by yantom** [comment]
Oprava nasazena. Pro jistotu v GUI prosím použijte ctrl+f5 pro reload bez cache.

Ještě jsem si Všiml že oproti původnímu zadání má role pro potvrzování mazání možnost otestovat stav balíčku na úložišti - řádek 25 https://docs.google.com/spreadsheets/d/16FW0v0bFdKAKw-tj6iYrAA56Zer325RHrecuvh1lnWI/edit#gid=1441115808 . Momentálně může kdokoliv s oprávněním AIP_RECORDS_READ i testovat stav balíku na úložišti. Pokud bychom se chtěli držet původního zadání museli bychom vytvořit pro testování samostatné oprávnění. Prosím o info zda je OK současný stav nebo bude vhodné přidat nové oprávnění.

**Comment by kerschfilip** [comment]
Myslím, že současný stav je OK, není třeba přidávat nové oprávnění

**Comment by yantom** [comment]
V odkazovaném dokumentu jsem tedy přidal upřesnění "Can test AIP state at logical storage." i do sloupce role pro potvrzování mazání. Děkuji.
