### ISSUE TITLE
Zakládání nových uživatelů a datum úprav účtů

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#75]
**Založení nového uživatele**
Rád bych se zeptal, jak funguje zakládání nových uživatelů skrze frontend. Po kliknutí na `nový` je možné vyplnit uživatelské jméno a v roli superadmina i dodavatele, ale nerozumím tomu, kde vezme uživatel heslo pro přihlášení. Poprosil bych o doplnění informací do wiki - nebo mě na ně, prosím, naveďte, bohužel jsem je nenašel

**Nefunguje datum úpravy uživatelského účtu**
V souvislosti s tím jsem si také všiml, že asi nefunguje položka `upraveno` v detailu konkrétního uživatele - například můj profil _kersch_ byl upraven dnes ráno (změna uživatelských rolí skrze účet _arc-bob_), ale pod upraveno je stále datum z minulého roku

**Comment by yantom** [comment]
Uživatel je při vstupu do systému autentizován vůčit LDAPu, tedy musí již mít učet v něm, heslo dostane od administrátora LDAP. Zakládání účtu v LDAP skrze Arclib není podporováno.
Pokud se do ARCLib přihlásí uživatel poprvé, je mu automaticky založen účet bez oprávnění a administrátor musí následně přiřadit oprávnění a producenta. Agenda založení uživatele je pouze obdoba tohoto procesu, kdy administrátor může zaregistrovat uživatele a přiřadit mu role a producenta dřív, než se se uživatel poprvé přihlásí. Následně po přihlášení může již uživatel pracovat a nemusí čekat na přiřazení. **Aktualizujeme WIKI**

Datum úpravy je aktualizováno pouze při úpravě samostatné entity, nikoliv vazeb, přičemž oprávnění jsou vazby. Pokud to bude nutné, lze toto v tomto případě doimplementovat.

**Comment by yantom** [comment]
Doplněno do wiki https://github.com/LIBCAS/ARCLib/wiki/Usage@Users . Navíc je teď aktualizována časová značka úpravy uživatele i při přiřazení role.

**Comment by kerschfilip** [comment]
Děkuji! Informace jsou doplněny, časová značka funguje, takže issue zavírám
