### ISSUE TITLE
Problém s uložením na Archival Storage - nedostupný CEPH?

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#76]
Nedaří se mi vložit SIP jinak než v debugging modu (například [tady](https://arclib-test.lib.cas.cz/ingest-workflows/ARCLIB_000000914) )
Vrací se chyba 

> couldn't execute activity <serviceTask id="ServiceTask_1snmjbd" ...>: workspace/ARCLIB_000000914/abd005-0000ti (12).zip (No such file or directory)

Zdá, se že všechny události probíhají úspěšně, chyba nastane (asi) při ukládání na Archival Storage - při zapnutém debugging mode se balík uloží bez problému.

zdá se, že CEPH je nedosažitelný (je to tak?) 
![image](https://user-images.githubusercontent.com/57805328/77893493-49506600-7274-11ea-9128-527463bfe37c.png)

neměla by chyba při ingestu způsobená selháním ukládání na Archival Storage, hlásit něco jako `ARCHIVAL_FAILURE` nebo něco podobného - aby uživatel věděl, kde se stala chyba?

**Comment by yantom** [comment]
Děkuji za nahlášení, CEPH by měl být dostupný, tato chyba bude mít předpokládám jiný důvod.

**Comment by yantom** [comment]
Chybu se nám v nové verzi nepodařilo zreprodukovat. [Balíček jsme úspěšně zingestovali.](https://arclib-test.lib.cas.cz/ingest-batches/60ea8c40-408f-43cf-b633-5479a3e6d1df). Chyba se vyskytla ještě před odesláním do Archival Storage, tedy nedostupnost CEPHu zde nehrála roli. Prozatím považujeme za vyřešené.
