### ISSUE TITLE
Absolutní / a relativní ./ cesty v filesec

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#77]
Nedaří se mi vložit SIP balíčky, které by dle mého názoru měly bez problému projít. Arclib hlásí "No value present" 

![image](https://user-images.githubusercontent.com/26278424/77943144-0cf52800-72bd-11ea-9ae0-ab1d0f2c0788.png)

Porovnala jsem balíček, který neprošel s touto hláškou a balíček, který prošel bez problému a nejsou v nich významné rozdíly. Je možné zjistit proč balíčky neprochází a upravit hlášku, místo "No value present"  na něco konkrétnějšího?

Na No value present neprošly tyto:
ARCLIB_000000924
ARCLIB_000000905

a další. 

Zkousela jsem i "vypnout" cast kroku v SIP profilu, aby byly pozadavky na balicky co nejmensi, ale stale neprochazi na No value present.

**Comment by godnat** [comment]
Zdá se, že problém bude (alespon pro některé balíčky) v hlavním mets souboru v sekci <mets:fileSec>, kde v  _mets:fileGrp/mets:file/mets:Flocat_ je odkaz na soubor zapsán _./mastercopy/mc_xbs008-00043a_0083.jp2_, vadí tam tečka a lomítko na začátku, když jsme to v balíčcích opravili na: mastercopy/mc_xbs008-00043a_0083.jp2, balíčky prošly. Je možné nastavit aby Arclib umět pracovat i se zápisy cest _./mastercopy/mc_xbs008-00043a_0083.jp2_  a  _/mastercopy/mc_xbs008-00043a_0083.jp2?_ 
Možná to jde nějak zapsat v SIP profilech, ae netuším jak.

**Comment by yantom** [comment]
Děkujeme za detailní popis issue. V SIP profilu se toto nastavit nedá, jednalo se o nedostatek aplikace. Podpora byla doimplementována a nasazena. Vybrali jsme balíček z předchozího ingestu _ARCLIB_000000924_ a úspěšně prošel v novém ingestu _ARCLIB_000001020_

**Comment by godnat** [comment]
Otestováno, prošly balíčky jež měly cestu uvedenou _./amdsec_ i _/amdsec_. Díky.

**Comment by yantom** [comment]
Pro jistotu otvírám ještě jednou s komentářem. 

U relativních cest (začínajících **./**) je současná implementace určitě vyhovující. Problém může nastat u absolutních cest  (začínajících **/**) v případě že se jedná o NDK zabalený v PROARC.

Absolutní cesty chápeme klasicky jako "cesty od počátku" kde jako počátek bereme kořen balíčku. Při zabalení NDK do PROARC se však kořen mění, a cesty které byly v původním NDK METS zadány absolutně pravděpodobně přestanou fungovat (předpokládám že cesty při vkládání do PROARC neupravujete). Bylo by dobré toto zkontrolovat.

**Comment by kerschfilip** [comment]
Nejsem si jistý, co přesně má být zkontrolováno, můžete mne, prosím, navést?

cesty v NDK _mets*.xml_ jsou v našich archivních balíčcích zapsány například následovně: `amdsec/amd_mets_aba007-0000cf_0007.xml` - je to tak proto, že NDK složku v archivním balíčku z ProArcu má být možné "vyndat" a použít jako samostatný NDK balíček. Pro _mets_ v NDK složce je tak za kořenovou považována právě NDK složka 

Vzhledem k tomu, že celé archivní balíčky jsou zabaleny do bagitu, předpokládám ale že pro kontrolu fixity a tvorbu fileSec je používán soubor _manifest-md5.txt_ a ne _mets_ z NDK složky. Alespoň jsem se nesetkal zatím s žádnou chybou při zpracování balíčku. fileSec v ARCLib AIP XML se také zdá být v pořádku. Cesty jsou zapsány například takto:
`data/NDK/aba007-0000cg/amdsec/amd_mets_aba007-0000cg_0025.xml`

**Comment by yantom** [comment]
Z popisu @godnat jsem pochopil že v nativním NDK balíčku může být cesta uvedena třemi způsoby:

1) `amdsec/amd_mets_aba007-0000cf_0007.xml`
2) `./amdsec/amd_mets_aba007-0000cf_0007.xml`
3) `/amdsec/amd_mets_aba007-0000cf_0007.xml`

První dva případy jsou OK ale třetí bude pravděpodobně způsobovat problém. Jako nejsprávnější řešení se mi jeví takto zapsanou cestu přepsat na formát 1. či 2. příkladu ještě před zasláním do ARCLib.

**Comment by yantom** [comment]
Vzpomenuto na meetingu. Případů kdy jsou cesty zapsány třetím způsobem by mělo být minimum. V případě že se objeví, je řešením úprava vstupního balíčku. Prozatím tedy zavírám, pokud by zde bylo co k řešení prosím o znovuotevření.
