### ISSUE TITLE
extracted format size - Chyba při ingestu balíčku

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#78]
Při ingestu NDK balíčku (monografie v. 1.3.2.) jsem se setkal s touto chybou:

> Error from server at http://147.231.118.145:8983/solr/arclibXmlC_shard1_replica_n1: ERROR: [doc=ARCLIB_000000933_extracted_format_0] Error adding field 'extracted_format_size'='3324682632' msg=For input string: "3324682632"; nested exception is org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://147.231.118.145:8983/solr/arclibXmlC_shard1_replica_n1: ERROR: [doc=ARCLIB_000000933_extracted_format_0] Error adding field 'extracted_format_size'='3324682632' msg=For input string: "3324682632"

Prosím, co by mohlo být příčinou chyby? Kontroloval jsem údaje o velikostech ve vstupních datech a nenašel jsem odchylky oproti datům, která v minulosti prošla bez problému.

**Comment by yantom** [comment]
Šlo o přetečení nevhodně zvoleného datového typu. V schématu indexu jsme zaměnili int->long, chyba by se již neměla vyskytovat.

**Comment by jbil7** [comment]
Vyzkoušeno na témže balíčku a chyba se již nevyskytuje. Děkuji!
