### ISSUE TITLE
Návrh na změnu mapování "authorial ID" pro NDK balíčky

### ISSUE THREAD

**Issue by vjirousek** [LIBCAS/ARCLib#79]
Dle domluvy na předchozí schůzce přikládám návrh pro změnu mapování "authorial ID" - namísto stávajícího info.xml by mělo být přebíráno z hlavního METS souboru dle následujících podmínek:

### MONOGRAFIE:

odkud: hlavní_mets.xml
identifikace monografie dle kořenového elementu: <mets:mets TYPE="Monograph">

zdroj pro "authorial ID":

var 1) 
<mets:dmdSec ID="MODSMD_VOLUME*">
<mods:identifier type="uuid">**df53c210-d3f7-11e6-a1de-001018b3eb4b**</mods:identifier>

pouze pokud MODSMD_VOLUME není v balíčku obsaženo, pak:

var 2) 
<mets:dmdSec ID="MODSMD_SUPPL*">
<mods:identifier type="uuid">**df53c210-d3f7-11e6-a1de-001018b3eb4b**</mods:identifier>

### PERIODIKA:

odkud: hlavní_mets.xml
identifikace periodika dle kořenového elementu: <mets:mets TYPE="Periodical"> 

zdroj pro "authorial ID":

var 1) 
<mets:dmdSec ID="MODSMD_ISSUE*">
<mods:identifier type="uuid">**df53c210-d3f7-11e6-a1de-001018b3eb4b**</mods:identifier> 

pouze pokud MODSMD_ISSUE není v balíčku obsaženo, pak:

var 2) 
<mets:dmdSec ID="MODSMD_SUPPL*">
<mods:identifier type="uuid">**df53c210-d3f7-11e6-a1de-001018b3eb4b**</mods:identifier>

**Comment by vjirousek** [comment]
Doplnil jsem variantu pro samostatně zpracovanou přílohu monografie, vyskytuje se velmi zřídka, ale standard s ní počítá.

**Comment by yantom** [comment]
Budou implementovány rozšířené možnosti mapování postihující zmíněné případy užití.

**Comment by yantom** [comment]
@vjirousek 
Implementováno zavedením podpory Xpath 3.1. Požadovaný xPath jsem vložil do profilu Sip profile 1 https://arclib-test.lib.cas.cz/sip-profiles/3cdc21a2-8b2a-4b56-81a8-3d2ee82ab6b4 a provedl testovací ingest: https://arclib-test.lib.cas.cz/ingest-workflows/ARCLIB_000003175

Xpath:

```
if (/mets/@TYPE = 'Monograph') then 
	if(/mets/dmdSec[starts-with(@ID,'MODSMD_VOLUME')]//identifier[@type='uuid']/text())
		then /mets/dmdSec[starts-with(@ID,'MODSMD_VOLUME')]//identifier[@type='uuid']/text()
	else
		/mets/dmdSec[starts-with(@ID,'MODSMD_SUPPL')]//identifier[@type='uuid']/text()
else
	if(/mets/@TYPE = 'Periodical') then
		if(/mets/dmdSec[starts-with(@ID,'MODSMD_ISSUE')]//identifier[@type='uuid']/text())
			then /mets/dmdSec[starts-with(@ID,'MODSMD_ISSUE')]//identifier[@type='uuid']/text()
		else
			/mets/dmdSec[starts-with(@ID,'MODSMD_SUPPL')]//identifier[@type='uuid']/text()
	else
		null
```

**Comment by jbil7** [comment]
Dle mých zjištění probíhá již mapování authorial ID v souladu s návrhem. Testoval jsem prozatím pouze na perio (s hlavní úrovní na issue i na suppl), nicméně s ohledem na užitý xpath usuzuji, že bude analogicky funkční i pro mono.

**Comment by yantom** [comment]
Mělo by tomu tak být, interně jsme testovali všechny případy.
