### ISSUE TITLE
Externí ID v ingest workflow

### ISSUE THREAD

**Issue by pavlaskovae** [LIBCAS/ARCLib#8]
V popisu ingest workflow se vyskytuje hodnota externí ID, která se zdá být přidělována interně ARCLibem. V dokumentaci jsem našla External ID v Producent profiles (unique identifier of a producer profile, incremental value of integer type), což je ale očividně jiná hodnota. Není to špatně namapované?
![externi_id](https://user-images.githubusercontent.com/5365793/51611501-ad182a00-1f1f-11e9-9953-08e529079ec3.jpg)

**Comment by hochla-simon** [comment]
External ID u Ingest workflow a external ID u Producer profilu sú dva nezávislé atribúty. Sú prideľované interne systémom, no slúžia ako externý identifikátor entit, preto je použitý názov external ID.

V systéme interne používame na previazanie entít v databáze premennú s názvom id typu UUID, nezobrazuje sa na frontende.  Je to tak kvôli robustnosti, v prípade, že by bolo potrebné napríklad migrovať dáta z inej inštancie Arclibu, aby nedošlo ku kolízií identifikátorov entít.

**Comment by hochla-simon** [comment]
Uvedená chyba - nezhodujúce sa External ID vo formulári a v URL stránky - bola vyriešená spolu s ticketom https://github.com/LIBCAS/ARCLib/issues/12.
