### ISSUE TITLE
Nelze ingestovat BAGIT

### ISSUE THREAD

**Issue by yantom** [LIBCAS/ARCLib#80]
Vytvořeno na základě komentářu v #65 

yantom commented 27 days ago
BAGIT balíček na vstupu by v zásadě měl fungovat. V současnosti by mělo stačit v SIP profilu změnit typ SIP balíku a upravit GLOB výrazy - přidat složku data do cest k souborům, např. pro tento profil: http://inqooltest-arclib.libj.cas.cz/sip-profiles/688e2510-490d-11ea-87a9-c5406a24266f změnit výrazy na:

data/info*.xml
data/['mets', 'METS']*.xml

@kerschfilip
 
kerschfilip commented 26 days ago
Bohužel se mi nedaří BAGIT vložit. Použil jsem doporučené nastavení, ale ingest (například ingest-workflows/ARCLIB_000000832) skončí okamžitě chybou

File with metadata for ingest workflow with external id ARCLIB_000000832 does not exist at path given by glob pattern: data/['mets', 'METS']*.xml

Když jsem zkusil upravit glob výrazy, takto:
Path to XML: mets*.xml
Path to main metadata file: mets*.xml
a Typ SIP: BAGIT
tak ingest započne (takže ARCLib asi ví, že data má v případě BAGIT hledat ve složce data?), ale selže až po procesu extrakce metadat s chybou:

No value present
java.util.NoSuchElementException: No value present
...

jde například o ingest-workflows/ARCLIB_000000836

**Comment by yantom** [comment]
@kerschfilip 

V případě BAGIT se jednalo o kombinaci chyb a nejasné specifikace. 

BAGIT SIP by měl splňovat obecný formát SIPu - ten byl na wiki popsán na místě kde by ho člověk nehledal, vytvořil jsem proto novou stránku [Sip Format](https://github.com/LIBCAS/ARCLib/wiki/Sip-Format). Vámi ingestovaný obsah zipu by měl být správně ještě zabalen v složce s identickým názvem jako je samotný .zip (bez přípony). Při dodržení tohoto bude nutné cesty v SIP profilu uvést s _data/_ . 

Váš balíček jsem přebalil a s novými IQ profily byl úspěšně ingestován v novém ingestu _ARCLIB_000001024_ (úspěšnému ingestu předcházelo pár neúspěchů když jsme hledali správný profil).

**Comment by kerschfilip** [comment]
Díky! Podařilo se mi několik BagItů ingestovat, budu dál testovat, ale zdá se, že vše je OK

**Comment by kerschfilip** [comment]
ingest BAGITů funguje, issue může být zavřeno. Díky!
