### ISSUE TITLE
Filtrování ingestů dle jména uživatele

### ISSUE THREAD

**Issue by pavlaskovae** [LIBCAS/ARCLib#82]
V tuto chvíli je v rámci ingestu možné filtrovat spuštěné ingesty dle dodavatele dat. Nicméně, v rámci jednoho dodavatele může data vkládat několik uživatelů. Bylo by užitečné umožnit i filtrování dle jména konkrétního uživatele.
Uživatel by tak dostal rychle a přehledně informaci o stavu jím zadaných ingestů.

**Comment by yantom** [comment]
Tato možnost zde již je, jedná se o filtr s labelem: _Jméno zodpovědné osoby_ (v horní části formuláře).

**Comment by yantom** [comment]
Omlouvám se za nedorozumění, filtrování je nyní implementováno pouze v AIP XML search formuláři, v sekci ingestů bude doplněno.

**Comment by yantom** [comment]
Implementováno (v záhlaví vedle řazení).

**Comment by pavlaskovae** [comment]
Měla bych jen jednu drobnou poznámku - mohla by vyhledaná hodnota (jméno uživatele) být někde zobrazena? Ideálně by mohla zůstávat ve vyhledávacím poli stejně jako se to děje v sousedním poli.

**Comment by yantom** [comment]
Upraveno, jméno již zůstává předvyplněno ve filtru.

**Comment by pavlaskovae** [comment]
Potvrzuji, že funguje. Navrhuji uzavřít.
