### ISSUE TITLE
Možnost změnit Validační profil v případě pádu ingestu.

### ISSUE THREAD

**Issue by yantom** [LIBCAS/ARCLib#84]
Implementace je zdá se reálná, znamenala by přesun validačního profilu z dodavatelského profilu do workflow configu.

**Comment by kerschfilip** [comment]
Díky za informaci! Alespoň podle mne by přesun nastavení validačního profilu do konfigurace workflow neznamenal nijak velký problém pro běžné používání arclibu. 

Nyní je možná spíše k diskuzi jak moc je tato funkcionalita užitečná. Sám si nejsem jistý, jak často by nastávaly případy, kdy by byla skutečně využívána. Jen připomenu, že možnost změnit validační profil při pádu ingestu vychází z funkčních požadavků zadávací dokumentace - více #73

**Comment by yantom** [comment]
Bude implementováno.

**Comment by yantom** [comment]
Implementováno, viz https://github.com/LIBCAS/ARCLib/wiki/Ingest-workflow#validator-1

**Comment by kerschfilip** [comment]
otestováno, viz #73
