### ISSUE TITLE
Jednotný způsob výběru profilu dodavatele při ingestu

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#85]
Napadlo mě, zda by nebylo uživatelsky přívětivější sjednotit způsob výběru profilu dodavatele při ingestu - zatímco při vkládání jednoho SIP se profil dodavatele vybírá podle externího ID, při zakládání rutiny se vybírá podle názvu. Výběr podle názvu se mi zdá jako lepší varianta, nebo existuje nějaký důvod pro současné nastavení, kterého jsem si nevšiml? Díky

**Comment by yantom** [comment]
Implementováno a nasazeno.

**Comment by kerschfilip** [comment]
Otestování, funguje. Děkuji!
