### ISSUE TITLE
Viditelnost pole Označení/Label ve výsledcích vyhledávání

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#86]
Myslím, že na jedné ze schůzek již tento nápad padl. Protože jako authorial ID bude používáno UUID (případně jiný identifikátor) - viz #79 , budou při vyhledávání AIP ve výsledcích pro člověka jen ne příliš vypovídající identifikátory (autorské ID a AIP ID přidělené ARCLibem). Pro lepší a příjemnější orientaci ve výsledcích by tak bylo fajn přidat sloupec “Označení/Label”, který se nyní zobrazuje až po rozkliknutí konkrétního výsledku.

**Comment by yantom** [comment]
Implementováno a nasazeno.

**Comment by kerschfilip** [comment]
Díky! Vypadá to dobře. Považuji za vyřešené a issue zavírám.
