### ISSUE TITLE
Nefunkční deletion request

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#87]
Ve snaze otestovat možnost fyzického smazání AIP balíčku jsem při zadání požadavku "Delete AIP" narazil na tuto chybu:

> 500 Error
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'DELETE' not supported

Samotné "Deletion requests" nejsou dostupné:

> 404 Error
MissingObject{type=cz.cas.lib.arclib.domain.ingestWorkflow.IngestWorkflow, id='list_deletion_requests'}

Testováno na `ARCLIB_000001007`

**Comment by yantom** [comment]
Sekce je opět v provozu.

**Comment by jbil7** [comment]
Funguje, děkuji!
