### ISSUE TITLE
Sledování vývoje reportingu

### ISSUE THREAD

**Issue by pavlaskovae** [LIBCAS/ARCLib#88]
Reporting podléhá připomínám z více stran, považujeme tedy za vhodné soustředit připomínky v tomto issue, kde budeme zároveň všichni moci sledovat vývoj. Prosím relevantní osoby o vyjádření  @kerschfilip @vjirousek 

Zadávací dokumentace specifikuje, že: 
a) generování reportů lze automatizovat a nastavit čas generování, 
b) výstup reportů lze ukládat v Excelu, PDF, CSV

**Comment by vjirousek** [comment]
Tady bylo zadání pro úvodní nastavení:
https://docs.google.com/document/d/1Z0Z26IzjBMw4BoVOq4s4Gi21V4GeslIbOT6qNKZ6ZOI

Tady je ukázka zaslaná 14. května 2019 (jedná se o statistiku uložených souborových formátů): 
https://drive.google.com/file/d/18IBL0T-EQ5-hElM89ILXYw62pdEuAJ6J/view?usp=sharing

Jinak si nejsem si jistý zda, jak a kam lze aktuálně statistiky generovat.

**Comment by vjirousek** [comment]
Tak tady by měla být aktuální únorová ukázka:
https://drive.google.com/drive/folders/1T0BfDdHlrRbBc0OX0w02dkjC9V6jGA-q

**Comment by yantom** [comment]
První verze agendy reportů je nasazena.

**Comment by kerschfilip** [comment]
V současné verzi je možné generovat reporty o ingestu, formátech a scanerech.
- v reportu o ingestu (dataimport) jsou trošku podivná čísla - například průměrný ingest prý trvá asi 1700 minut 
- taky se zdá, že report formátů úplně nereportuje skutečnost 
Například v balíčku https://arclib-test.lib.cas.cz/aip/ARCLIB_000001260 je MP4 soubor (fmt/199), ale ve statistikách se neukazuje

Bylo by možné zkontrolovat, kde se tyto informace berou a zda jsou korektní?

...a jen poznámka - při srovnání se zadávací dokumentací neumí současná verze generovat reporty týkající se dodavatelů, dat uložení, použitých workflow, typů eventů a chyb ignorovaných při zpracovávání a také informací o Accessu. Nevím, jak moc jsou všechny tyto statistiky potřeba, ale například informace týkajících se jednotlivých dodavatelů by možná nebyly špatné, stejně jako případně možnost omezit stávající reporty (formáty, ingest,...) na jednotlivé dodavatele. Možná by nebylo špatné, aby každý report obsahoval datum vytvoření (někde v hlavičce).

Nyní také není možné reporty generovat automaticky ve stanovený čas.

**Comment by yantom** [comment]
Děkujeme za revizi.

1) Průměrná doba ingestu v dataimport reportu bude pravděpodobně způsobená specifiky testovacího prostředí, konkrétně zde asi budou některé balíčky jejichž ingest se na dlouho zaseknul na nevyřešeném incidentu. Zamyslíme se nad tím jak lépe v statistikách promítnout skutečnost že ingest může být pozastaven.

2) Nepřítomnost mp4 v reportu bude chyba, musíme prověřit.

3) Informace se berou z DB pro reporty s nastavením *ARCLib XML index report = false*, v opačném případě se berou z indexu. Konkrétní sekce ingestu/tabulky lze vyčíst z JRXML reportu v sekci pro definici datasetu. 

4) Reporty byly navrhnuty jako uživatelsky definované aby mohl administrátor dle potřeb kdykoliv vytvořit další typ reportu. Jako dodavatelé jsme prozatím vytvořili 3 konkrétní reporty dle zadání od @vjirousek . Pokud máme tvořit další, potřebovali bychom přesné zadání.

5) Čas vygenerování přidáme do hlavičky reportu.

6) Reportování ve stanovený čas bude implementováno.

**Comment by yantom** [comment]
Bod 5 implementován. 
Bod 6 implementován v nových notifikacích. U notifikací je nyní možné zvolit typ - notifikace o revizi formátu nebo notifikace zasílající report. Dále je možné zvolit kterých reportů nebo formátů se má notifikace týkat. Stejně jako u předchozí implementace notifikací je perioda / čas notifikace nastaven CRON výrazem a email je zaslán všem uživatelům s rolí admin / superadmin.
Body 1 a 2 řešíme.

**Comment by yantom** [comment]
K bodu 2 - mp4 není v reportu zahrnuto, jelikož report je postaven nad daty extrahovanými ze vstupních metadatových souborů (složka amdsec) pomocí XSL (tedy řádky 28-39 zde: https://docs.google.com/spreadsheets/d/1OR_NyrTfajZo5emu4PV2c0-pA3D6s2E6lcyx2cJXzLU/edit#gid=586517350), nikoliv nad formáty identifikovanými ARCLibem (řádky 40-46) v procesu ingestu. Mp4 soubor není v vstupních amdsec popsán. Otázkou je k čemu má report sloužit, zda k přehledu popisu od původce nebo stavu v systému, zadání toto nespecifikovalo. Extrahovaných atributů je více než těch generovaných (preservationLevel, creatingApplication etc.).

Příklad extrahovaných metadat:
```xml
<ARCLib:format>
  <ARCLib:fileFormat>image/tiff</ARCLib:fileFormat>
  <ARCLib:formatVersion>1.0</ARCLib:formatVersion>
  <ARCLib:formatRegistryKey>fmt/353</ARCLib:formatRegistryKey>
  <ARCLib:formatRegistryName>PRONOM</ARCLib:formatRegistryName>
  <ARCLib:creatingApplicationName>ProArc</ARCLib:creatingApplicationName>
  <ARCLib:creatingApplicationVersion>3.5.16</ARCLib:creatingApplicationVersion>
  <ARCLib:dateCreatedByApplication>2020-03-10</ARCLib:dateCreatedByApplication>
  <ARCLib:preservationLevelValue>deleted</ARCLib:preservationLevelValue>
  <ARCLib:fileCount>9</ARCLib:fileCount>
  <ARCLib:size>23642986</ARCLib:size>
</ARCLib:format>
```

Příklad generovaných metadat:
```xml
<ARCLIB:format>
  <ARCLIB:formatRegistryKey>fmt/101</ARCLIB:formatRegistryKey>
  <ARCLIB:formatRegistryName>PRONOM</ARCLIB:formatRegistryName>
  <ARCLIB:creatingApplicationName>DROID</ARCLIB:creatingApplicationName>
  <ARCLIB:creatingApplicationVersion>DROID: version: 6.4, Signature files: 1. Type: Binary Version: 91 File name: DROID_SignatureFile_V91.xml 2. Type: Container Version: 20170330 File name: container-signature-20170330.xml</ARCLIB:creatingApplicationVersion>
  <ARCLIB:dateCreatedByApplication>2020-05-07</ARCLIB:dateCreatedByApplication>
  <ARCLIB:fileCount>70</ARCLIB:fileCount>
</ARCLIB:format>
```

**Comment by kerschfilip** [comment]
Bod 5 ověřen, čas vygenerování je v hlavičce reportu

Bod 6 se mi ověřit nepovedlo, zdá se, že notifikace nějak emaily neposílají

k bodu 2 - děkuji za vysvětlení. Pokud tomu dobře rozumím, tak data, která nejsou v amdsec popsána nejsou do reportu vůbec zahrnuta. To se mi nezdá v případě ProArc balíčku ideální, protože relativně velké množství dat zde bohužel popsáno není. Report potom tudíž nemůže být kompletní. Řešením by mohlo být udělat dvě verze reportů - jednu, která bude zohledňovat informace od dodavatele, a druhou, která bude pracovat s daty generovanými ARCLibem (zde ale budou chybět některé informace jako například PreservationLevel).

**Comment by yantom** [comment]
6 - opraveno - jednalo se o chybu v konfiguraci emailové služby
2 - začneme tedy pracovat na druhé verzi reportů

**Comment by yantom** [comment]
Upravený report pro formáty je nasazen na TEST server. Předvytvořené reportovací šablony jsou nyní odkázány i z wiki: https://github.com/LIBCAS/ARCLib/wiki/usage@reports
