### ISSUE TITLE
Přidání elementu do ArclibXML a odpovídajícího mapování do SIP profilu

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#89]
Toto je i k diskuzi řešitelského týmu, zda je úprava nutná:

V případě některých balíčků de do ArclibXML nedostane informace o použitém skeneru (scannerModelName), uživatelé by ale mohli potřebovat vyhledat balíčky dle skeneru na kterém se skenovalo(?). Do ArclibXML se to nedostane proto, že skener není samostatně popsán v elementu premis:agent.  

Tato informace by se mohla dát do SIP profilu do části ARCLIB_001 mezi elementy ARCLib:preservationLevelValue a ARCLib:scannerModelSerialNo, mapování by mělo vést sem: mix:ImageCaptureMetadata/mix:ScannerCapture/mix:ScannerModel/mix:scannerModelName.

**Comment by godnat** [comment]
Zmíněno zde: https://github.com/LIBCAS/ARCLib/issues/97
Pokud si dobře pamatuji, na předminulé schuzce se odsohlasilo, že se element přidá v issue https://github.com/LIBCAS/ARCLib/issues/97 je uvedeno, kam by se mohlo přidat.

**Comment by yantom** [comment]
Považuji za vyřešené v #97

**Comment by godnat** [comment]
Otestováno, údaj se do ArclibXML extrahuje, děkuji. Považuji za vyřešené.
