### ISSUE TITLE
ArclibXML sloučení stejných elementů

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#9]
V ArclibXML  v sekci  <METS:techMD ID="ARCLIB_004"> prosíme o sloučení elementů.

Např. místo tohoto: 
![arclib_004](https://user-images.githubusercontent.com/26278424/51621417-c24b8380-1f34-11e9-918b-fc09fa058945.jpg)

takto:
![arclib_004b](https://user-images.githubusercontent.com/26278424/51621490-ead37d80-1f34-11e9-82fb-518c2107b42a.jpg)

**Comment by hochla-simon** [comment]
Opravené, chyba sa nachádzala v SIP profile: dáta sa zgrupovali podľa **date time created**, no vo výsledku sa vypísalo u každej skupine iba **date created**, zjednotené na **date created** na oboch miestach.
