### ISSUE TITLE
Přidání info o SIP profilech a validačních profilech do ArclibXML

### ISSUE THREAD

**Issue by godnat** [LIBCAS/ARCLib#91]
K diskuzi:
V Arclib XML je informace o dodavateli (př. ústav geologie), pod jedním dodavatelem by ale mohlo být zřejmě víc profilů dodavatele a v nich jsou pak jednotlivé SIP a validační profily- informace o použitých SIP profilech a validačních profilech v ArclibXML není, jestli by nestálo za to, mít tam i tuto informaci.

**Comment by kerschfilip** [comment]
Myslím, že by stálo za to mít informace o použitých SIP a validačních profilech v AIP XML a napadá mě, zda by potom nebylo možné použít je i jako způsob vyhledávání AIP. Díky!

**Comment by godnat** [comment]
Jedna z možností, kam by to šlo napsat by mohla být událost ingestion a dát to do detailu události.

**Comment by yantom** [comment]
Souhlasím s implementací, a ponechávám k diskuzi kam umísti. Event **ingestion** v současné době negenerujeme.

**Comment by yantom** [comment]
Profily budou odkázány z samostatných elementů v ARCLib NS.

**Comment by yantom** [comment]
Implementováno. Profily jsou nyní v ARCLib XML a lze dle jejich externích ID vyhledat ve formuláři AIP search. Platí pouze pro nově ingestované balíčky. Lze ověřit zadnámi externího ID SIP profilu 44 https://arclib-test.lib.cas.cz/aip-search

**Comment by godnat** [comment]
Díky! Jestli to chápu správně, platí to nyní jen s použitím SIP 44, což je SIP pro Krameria, takový balík nemám, takže to ted nezkusím, (s jiným profilem se to do ArclibXML nezapsalo)
Dívala jsem se ale na balíky, které tam už někdo pod SIP 44 poslal a tam v metadatech je toto: 

<ARCLib:ingestProfiles>
              <ARCLib:producerProfile>46</ARCLib:producerProfile>
              <ARCLib:sipProfile>44</ARCLib:sipProfile>
              <ARCLib:validationProfile>27</ARCLib:validationProfile>
              <ARCLib:workflowDefinition>18</ARCLib:workflowDefinition>
</ARCLib:ingestProfiles>

Nenašla jsem v Arclibu profil Workflow definition č. 18 (nejsou u nich čísla a myslím, že jsem jich ta spočítala jen 16, ale možná se dívám na špatné místo).

A profilu producenta--číslo 46 odkáže na profil producenta, ale ten je editovatelný, takže ho můžu změnit a pak to neodpovídá. Ale to je na diskuzi, profil producenta můžu změnit jako Superadmin (možná jsme se tak kdysi dohodli vuz: https://github.com/LIBCAS/ARCLib/issues/117, takže asi ok?), jako archivář už třeba ne.

Podstatné že v Arclib XML je odkaz na SIP profil, validační profil a snad i definici workflow.

**Comment by yantom** [comment]
Vazba je v ARCLib XML všech balíků ingestovaných od dnes rána, na použitém profilu nezáleží. 
Číslo WF nevidíte pravděpodobně kvůli cache prohlížeče, zkuste prosím ctrl+f5, čísla byly definicím workflow přidány nedávno.
V současnosti jsou profily dle zadání v ARCLib XML a dá se dle nich vyhledávat, není však uložena přímo v DB. Pokud to bude nutné, můžeme toto do budoucna upravit aby byla i v DB.

**Comment by godnat** [comment]
Díky! Už to vidím u dalších balíčků je to taky, číslování u definice workflow vidím.
