### ISSUE TITLE
Chybná verze Arclibu v premis:agentNote (administrativní metadata arclibxml)

### ISSUE THREAD

**Issue by jbil7** [LIBCAS/ARCLib#92]
V administrativních metadatech ukládaných do ArclibXML jsem si všiml, že v elementu `<premis:agentNote>` se nachází verze 1.0.1. Pokud se nemýlím, tato verze byla aktivní přibližně na jaře roku 2019 a nyní používáme verzi 0.3.

**Comment by yantom** [comment]
Opraveno, v nově ingestovaných balících je uvedena verze 1.0 (release 1.0)

**Comment by jbil7** [comment]
Děkuji, ověřeno.
