### ISSUE TITLE
SIP z Kraméria

### ISSUE THREAD

**Issue by yantom** [LIBCAS/ARCLib#93]

**Comment by yantom** [comment]
@kerschfilip

Dle zadání byl vytvořen SIP profil: https://arclib-test.lib.cas.cz/sip-profiles/c783d6c0-3f28-11eb-bb48-332c4c323bc8

a otestován na 3 různých vstupech:

* periodikum exportované s parents FOXML (redukovaný balíček): https://arclib-test.lib.cas.cz/ingest-batches/b5bfeed6-aaea-4977-9899-1632103da450
* monografie: https://arclib-test.lib.cas.cz/ingest-batches/fbf0ba0b-b5b9-4ba8-b1bd-e68dddee29fd
* periodikum exportované bez parents FOXML: https://arclib-test.lib.cas.cz/ingest-batches/e5e29875-357b-4987-989c-aefc00710cff

**Comment by kerschfilip** [comment]
Otestováno, zdá se, že vše funguje, jak má. Mockrát díky!

Zkoušel jsem ještě ingestovat exporty z krameria zabalené jako bagit. Při tomto postupu se ale nevytváří správně label u periodik s parents FOXML - zatímco "normální" export má label např `A / Věda a výzkum:2020, 4:3, 09.09.2020`, když se stejný balíček vkládá jako BagIt label je jen `::3, 09.09.2020`. mohu poprosit o radu, jak by měl být SIP profil pro tuto variantu upraven? Děkuji

**Comment by yantom** [comment]
Záměnou 
<xsl:variable name="foxmls" select="collection(concat('file:///',$pathToSip,'?select=*.xml;recurse=no'))"/>
za
<xsl:variable name="foxmls" select="collection(concat('file:///',$sipMetadataPath,'/../?select=*.xml;recurse=no'))"/>

získáte profil který budete moci použít v obou (BAGIT i neBAGIT) případech.

**Comment by kerschfilip** [comment]
Bohužel v takovém případě vznikne při ingestu chyba:
```
couldn't execute activity <serviceTask id="ServiceTask_0fxsc9x" ...>: ARCLib incident: Ingest workflow internal runtime exception: net.sf.saxon.trans.XPathException: The file or directory file:////opt/arclib/workspace/ARCLIB_000003209/63c00fef-93f3-4be8-96e7-95ed79931252/data/63c00fef-93f3-4be8-96e7-95ed79931252.xml/../ does not exist
```

**Comment by yantom** [comment]
Omlouvám se, na toto už jsme asi kdysi narazili u NDK bagit, tak znovu a lépe:

```
<xsl:variable name="foxmls" select="collection(concat('file:///', string-join(tokenize($sipMetadataPath, '/')[position() lt last()], '/'),'/?select=*.xml;recurse=no'))"/>```

**Comment by kerschfilip** [comment]
Mockrát děkuji 

Budu samozřejmě dále testovat, ale myslím, že v tuto chvíli vypadá vše OK
