### ISSUE TITLE
BPM task validující MD5 ze všech .md5 souborů nacházejících se v SIP

### ISSUE THREAD

**Issue by yantom** [LIBCAS/ARCLib#94]

**Comment by yantom** [comment]
Do existujícího tasku pro kontrolu fixity byla doplněna automatická kontrola všech kontrolních součtů uvedených v souborech .md5 .sha1 .sha256 a .sha512 kdekoliv v SIP.

**Comment by jbil7** [comment]
Vyzkoušeno na .md5 souboru, jenž se nachází v NDK balíčku, a funguje. Díky!
