### ISSUE TITLE
Nastavení XSLT v SIP profilu pro archivní balíček z ProArcu

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#95]
[ARCLib AIP XML vytvořené při ingestu archivních balíčků z ProArcu (bagit)](https://arclib-test.lib.cas.cz/aip/ARCLIB_000001171) neobsahuje metadata, která mají být přebírána ze souborů `amd_mets*.xml`. Myslím, že je to tím, že tyto soubory jsou na jiném místě, než jsou očekávány: v NDK balíčku je cesta `SIP/amdsec` zatímco v proarcovském je to `SIP/data/NDK/*/amdsec`

Jak má být, prosím, upraven SIP Profil (XSLT), aby byla metadata přebírána? samotnému se mi to nedaří. Děkuji za pomoc!

**Comment by yantom** [comment]
Dobrý den, v tomto případě bude vhodné odrazit se od proměnné $sipMetadataPath (hlavní mets nalezený skrze GLOB v SIP profilu).

Možným řešením je tedy zaměnit stávající

```xml
<xsl:variable name="amdSecs"
                      select="document(//METS:fileGrp[@ID='TECHMDGRP']/METS:file/METS:FLocat/concat('file:///', $pathToSip, 'NDK/aba007-0000ce/amdsec?select=amd*.xml;recurse=no', @xlink:href))"/>
```
za
```xml
<xsl:variable name="amdSecs"
                      select="document(//METS:fileGrp[@ID='TECHMDGRP']/METS:file/METS:FLocat/concat('file:///', $sipMetadataPath,'/../',@xlink:href))"/>
```

**Comment by kerschfilip** [comment]
Díky moc za rychlou odpověď, bohužel se mi přes doporučené nastavení i další úpravy nedaří SIP profil nastavit a  `METS:amdSec/METS:techMD ID="ARCLIB_001-5" ` v AIP XML zůstávají prázdné. 

Zkoušel jsem na tomto[ SIP profilu](https://arclib-test.lib.cas.cz/sip-profiles/65dfd950-8858-11ea-8e7e-3dc57439605e) a [balíčku](https://arclib-test.lib.cas.cz/aip/ARCLIB_000001220)

**Comment by yantom** [comment]
Dobrý den, v použitém SIP profilu je třeba kromě proměnné zaměnit i následující argument dle předchozího komentáře: 'NDK/aba007-0000ce/amdsec?select=amd*.xml;recurse=no' -> '/../'

**Comment by kerschfilip** [comment]
Díky, to jsem zkoušel, ale i s nastavením přesně podle komentáře (níže) nejsou metadata převzata:

<xsl:variable name="amdSecs"               select="document(//METS:fileGrp[@ID='TECHMDGRP']/METS:file/METS:FLocat/concat('file:///', $sipMetadataPath, '/../',@xlink:href))"/>

**Comment by yantom** [comment]
Potvrzuji, jdu to odladit na lokálním stroji.

**Comment by yantom** [comment]
Daný přepis na lokálním stroji fungoval ale na linuxových nefunguje. Následující by již měl fungovat, vyzkoušeno na linuxe:

```xml
 <xsl:variable name="amdSecs"
                      select="document(//METS:fileGrp[@ID='TECHMDGRP']/METS:file/METS:FLocat/concat('file:///', string-join(tokenize($sipMetadataPath, '/')[position() lt last()], '/'),'/',@xlink:href))"/>
```

**Comment by kerschfilip** [comment]
Vyzkoušeno, funguje. Děkuji za pomoc!
