### ISSUE TITLE
Ingest stejného balíčku v debugging mode vede k chybě

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#96]
Při ingestu totožného balíčku, který již v arclibu je (stejná MD5, balíčky se nijak neliší) proběhnou všechny součásti ingestu v pořádku (asi až na uložení), Ingest Workflow hlásí stav `zpracováno` a dokonce je vytvořen i záznam ve Vyhledávání AIP
![image](https://user-images.githubusercontent.com/57805328/80218754-def7cf00-8641-11ea-8d16-343e6a1bbbb7.png)

Ovšem po nějaké době se stav změní na `Selhalo` , záznam ve Vyhledávání AIP zmizí. Hlášená chyba je: 

> couldn't execute activity <serviceTask id="ServiceTask_15sn5m2" ...>: ArchivalStorageException{status=404, body=MissingObject{type=cz.cas.lib.arcstorage.domain.entity.AipSip, id='c5221626-c9f2-4249-8f39-436ee1471145'}}

S chybou jsem se setkal pouze byl-li aktivován debugging mode. Například [zde](https://arclib-test.lib.cas.cz/ingest-workflows/ARCLIB_000001205)

**Comment by yantom** [comment]
Pravděpodobně přímá chyba verzování v debug módu. Pouze uvedu že stav *zpracováno* není koncový stav, tím je až stav *persistentní*. 

Předpokládám že v historické verzi bylo zapotřebí zapsat XML do indexu před uložením do Archival Storage, což by již nemělo platit. V rámci tohoto issue tedy pravděpodobně i přesuneme zápis do indexu z tasku ArclibXmlGenerator do StorageSuccessVerifier.

**Comment by yantom** [comment]
Verzování v debug módu opět funguje, přesun indexace z jednobo BPM tasku do druhého budeme řešit v novém issue #98

**Comment by kerschfilip** [comment]
Otestováno, verzování funguje. Děkuji za rychlou reakci!
